### ISSUE TITLE
cutefilewatch.h cannot be #included twice and implemented once since implementation/declarations are mixed erroneously

### ISSUE THREAD

**Issue by dseyedm** [RandyGaul/cute_headers#101]
hi randy

I cant access struct filewatch_t directly since it's not declared when I include it twice and define it in another source file.

it's a trivial issue to fix, just reorganize your source to have ALL of the definitions included under the CUTEFILEWATCH_H ifdefs

thanks

**Comment by RandyGaul** [comment]
I didn’t actually intend users to access it directly. What was your use case? Maybe I should rethink using an opaque pointer.

**Comment by dseyedm** [comment]
My apologies, I forgot that I was bypassing the default notification mechanism (filewatch_notify) to access filewatch->notifications directly. I felt it was more appropriate to loop through each notification rather than receive a callback without much context.

FYI: Here's a couple bugs I fixed in assetsys:
https://github.com/mattiasgustavsson/libs/pull/13
