### ISSUE TITLE
C2: point/dot support and C# port?

### ISSUE THREAD

**Issue by dsaf** [RandyGaul/cute_headers#102]
Hi, are there any plans and what is your opinion about supporting point-vs-something collision detection? This could be good for touch/click handling and maybe some particle physics. Circles could of course be used as a substitute, but still.

Also what would you say if someone ported C2 to C#? Do you have any recommendations about doing this? Situation with physics/collisions libraries in .NET is quite bad at the moment...

**Comment by RandyGaul** [comment]
Hi there! Point vs something should be done with the GJK function for click detection. There are two ways to use GJK in C2. First is to call the `c2GJK` function directly. The second option is to call a collide function with a circle and zero radius. For example `c2CircletoAABB` or `c2CircletoPoly`. These functions will internally call GJK appropriately for you.

C2 was written with porting in mind. Since the code is in plain C it is very easily portable to other languages. If anyone wants to contribute a port, I would happily lend my assistance however I can! It should be a relatively straight-forward one to one port to C#, for example.

**Comment by dsaf** [comment]
Thank you, I might give porting a try.

Tactically there are two options I see: 1) C++/CLI for .NET; 2) C# (with 7.0 ref improvements).

Strategically, what are your plans for the Cute/C2? Do you see this project as something you would maintain long-term? The reason I am asking is because a port maintenance would require either an equally deep understanding of collision math or keeping the code as close to the original as possible to make any fixes/improvements doable despite language barrier. Based on current "lean-header-file" philosophy I presume super-invasive "total" refactorings are not very likely in future?

Lastly, non-engine C# gamedev gravitates towards MonoGame framework. It has its own Vector2 and related types which means mapping/garbage overhead. Additionally there is a package management system in .NET world - NuGet. So it begs a question of which of the following are reasonable (probably all):

1) C# with all-Cute types -> single source file.
2) C# with all-Cute types -> compiled DLL.
3) C# with MonoGame-native types -> compiled DLL.

(Also a MonoGame runnable sample app port).

In terms of naming what does 'C2' stand for? I am guessing "Collisions in 2D"?

PS: I am not committing to anything and not expecting any commitment, just thinking and planning.

**Comment by RandyGaul** [comment]
C2 is really stable. It won't be changing. I was considering adding a couple new functions, but that's about it. Yep it means collision 2d. I'll be using C2 for a long time, so nobody has to worry about it changing or losing support.

Personally I think C# with all cute types in a single source file is the way to go. People can easily hook this up into their own Mono/Unity projects, and it's still accessible to C# in general.

DLL can work, but I don't think it's a great option. People aren't as used to using DLLs in C#, and I don't think it would make maintenance any easier.

**Comment by dsaf** [comment]
Understood, thanks.

DLLs (byte-code of course) are actually dominantly mainstream in general .NET, distributing and linking sources was popularised by Unity and is still rare outside of it. So I think both will be good. This might require additional juggling around reusable types like Vector2/Math/Matrices (so might be two code classes instead of one) but nothing impossible. Sorry if I sound stubborn here, it will be clearer for me once there is something compilable/runnable.

Most likely source of bugs will be doing by-value manipulation instead of by-reference, but I guess the only way is making an attempt and being attentive :).

I think the first step should be reproducing as closely as possible anyway. I had a quick first look:
1) C++/CLI is farther from C++ than I believed so it's not an option.
2) C# looks doable so far, though it will not be literally line-by-line. E.g. methods will have to move close to each other and so do enums/structs/consts. I guess it's all about retaining the shape of data and logic flow, the things around them (including names) can change. I might have to mess around with names to keep them C#-idiomatic (less abbreviations and also PascalCase).

As far as I understand forking doesn't make sense when making a port to a different language because it might confuse people and also because submitting pull requests / merging is not possible cross-language anyway? Additionally it will be C2 only here. Obviously it will retain the licence and clearly point towards the original. I am not really an active GitHub user so just want to make sure I am doing things according to etiquette.

**Comment by RandyGaul** [comment]
Well you're the expert here as I don't use C# regularly! I'd be happy to help either way :)

Pointers/references should be fairly trivial as advanced usage of pointers/references does not really exist in C2.

You can start a new repository to host your port, but I would also be perfectly happy hosting the version here. It would need to retain the original license info, but you can add a note saying you did the port so you can get credit for your work in this way.

**Comment by RandyGaul** [comment]
Hmm interesting. I do think sticking to features accessible from Unity will make your port a lot Moreno valuable. If people really wanted to avoid extra allocations they could just use C. And many people will want to stick with Unity accessible features, and this will become a deal breaker or a deference.

But in the end it is up to you of course! I’m just offering my opinion based on experience so far with these kinds of libs and using them to make games.

**Comment by dsaf** [comment]
Looks like they are sorting out C# 7 support fairly soon actually: https://unity3d.com/unity/roadmap . Backwards compatibility is a strong argument but I would not underestimate the appetite for optimisation even in higher-level languages.

I have a couple of questions if you don't mind and are not tired of my spamming yet:

1. What does "BARY" in ```C2_BARY``` stand for?
2. This is not a feature request, but have you considered pulling diagnostic visualisation methods from ```examples_cute_gl_and_c2``` into re-usable form e.g. ```cute_c2_diag.h``` (or ```_vis``` / ```_debug```)?

**Comment by RandyGaul** [comment]
Good idea actually. I have indeed considered placing those debug rendering utilities into C2. They are really useful! I also considered making a 2D debug drawing utility header, instead of placing one directly inside of C2. Both of these can be good options.

`C2_BARY` stands for barycentric coordinate. It's a linear combination. If you need help unrolling that macro, feel free to ask!

Since this feature may be coming to Unity soon, my recommendation would be: implement with Unity-safe features that are released right now, for the initial version. If/when Unity upgrades to 7, then it shouldn't be too difficult to roll out a new version. Of course, you can do this earlier, but I think the optimize the value you will get for your port, going the conservative route will really pay off :)

**Comment by dsaf** [comment]
I gave unrolling a try - is below correct (even if less effective - inlining is not guaranteed)?

```csharp
        private static c2v C2_BARY2(in c2Simplex s, float den, Func<c2sv, c2v> get) =>
            Maths.c2Add(Maths.c2Mulvs(get(s.a), (den*s.a.u)), Maths.c2Mulvs(get(s.b), (den*s.b.u)));

        private static c2v C2_BARY3(in c2Simplex s, float den, Func<c2sv, c2v> get) =>
            Maths.c2Add(
                Maths.c2Add(
                    Maths.c2Mulvs(get(s.a), (den*s.a.u)),
                    Maths.c2Mulvs(get(s.b), (den*s.b.u))),
                Maths.c2Mulvs(get(s.c), (den*s.c.u)));
```

In terms of pointer magic, I cannot understand below from ```c2GJK``` - is that effectively treating a struct as an array? Is it only limited to some members of that struct?

![image](https://user-images.githubusercontent.com/3845650/41489996-ea175c76-70e9-11e8-9599-158b160ec19a.png)

![image](https://user-images.githubusercontent.com/3845650/41489959-c134b934-70e9-11e8-8810-9fccea68d92e.png)

**Comment by RandyGaul** [comment]
Yeah that looks correct as far as I can tell just by glancing over it.

Yes, the idea is that the verts are an array as far as GJK can tell. But, it is also convenient to sometimes refer to the array elements directly as `a`, `b`, and `c`.

**Comment by RandyGaul** [comment]
Closing this out for now. Feel free to reopen later if you get any updates :)
