### ISSUE TITLE
cute_file: cf_get_ext starts at first period, not last.

### ISSUE THREAD

**Issue by xoorath** [RandyGaul/cute_headers#107]
A file formatted like `filename.alpha.beta` the extension will have the extension be `alpha.beta`, when I'd expect it should return `beta`.

A possible fix might be:
```
const char* cf_get_ext(cf_file_t* file)
{
	char* name = file->name;
	char* period = NULL;
	while (*name++) if (*name == '.')  period = name;
	if (period) cf_safe_strcpy(file->ext, period, 0, CUTE_FILES_MAX_EXT);
	else file->ext[0] = 0;
	return file->ext;
}
```

If you agree and like that solution I'll put in a PR.

**Comment by RandyGaul** [comment]
Nice catch! A PR would be very appreciated :)
