### ISSUE TITLE
MinGW problem in cute_tiled

### ISSUE THREAD

**Issue by dpeter99** [RandyGaul/cute_headers#116]
I have a program that runs fine on MSVC but gives segmentation fault error on MinGW
the line where the error occurs : 1261

![image](https://user-images.githubusercontent.com/7725817/47145125-4e606600-d2c9-11e8-8767-51a5b6df0f64.png)
![image](https://user-images.githubusercontent.com/7725817/47145150-60da9f80-d2c9-11e8-928c-b33d7e3a4f72.png)

here is the map file i'm trying to load
[Test-1-0 - Copy.txt](https://github.com/RandyGaul/cute_headers/files/2491166/Test-1-0.-.Copy.txt)

**Comment by chisaipete** [comment]
Can you provide more details about the calling code?  This in isolation isn't helpful, I've used that function successfully in my own game code previously. 😄

**Comment by RandyGaul** [comment]
Which compiler are you using, and version?

**Comment by RandyGaul** [comment]
Still having trouble? What compiler and version of compiler are you using? Are you running in 32 or 64 bit mode?

**Comment by RandyGaul** [comment]
Closing this out. Feel free to reopen if you need help.
