### ISSUE TITLE
Question/Help : Use with SFML in c++ and cute_tiled

### ISSUE THREAD

**Issue by willk24** [RandyGaul/cute_headers#120]
Hi can we use this with sfml in c++ ? I'm sorry if it's already writen or anything else but i spend 1/2 hours try to inplement it so now i asking for help and i'm a little lost with the documentation to understand how implement it. Thank.

**Comment by RandyGaul** [comment]
Which header are you trying to use?

**Comment by willk24** [comment]
cute_tiled

**Comment by RandyGaul** [comment]
Oh yeah you can definitely use cute_tiled. Just make sure to use the correct version of tiled. They recently changed their serialization format and broke backwards compatibility. Check out the examples if you need to see how to get things up and running.

If you get stuck feel free to ask more questions here :)

**Comment by willk24** [comment]
Maybe i don't correctly use cute_tiled ? 

cute_tiled_map_t* map = cute_tiled_load_map_from_file("Assets/Maps/map.json", nullptr);

I have to say that i don't really understand mem_ctx

**Comment by RandyGaul** [comment]
mem_ctx is for advanced usage. Set it to NULL. It’s just there for people that want to use a custom allocator, and override the cute tiled alloc/free functions.

What you have looks good to me. Just make sure you are using a version of Tiled cute tiled supports. The docs says I made sure it works up to version 1.1.5. If you use a newer version it may crash.

I will update cute tiled in the future to support latest version of Tiled.

**Comment by willk24** [comment]
I got the good version of tiled.

Just a late question how do you draw the tilemap ? I maybe miss a exemple

**Comment by RandyGaul** [comment]
You use SFML to do the drawing. You can use cute tiled to load up the tiles and get tile information, like the tile location and what image it uses. Then you use SFML for drawing and loading images.

**Comment by willk24** [comment]
Thank !

**Comment by RandyGaul** [comment]
No problem. Closing this out, but feel free to open it with more questions :)

**Comment by willk24** [comment]
Sorry byt did you have a idea ?
![image](https://user-images.githubusercontent.com/39808101/47809353-eede6d80-dd40-11e8-8e68-7566f215c187.png)
