### ISSUE TITLE
Help with cute_tiled: Sorry but did you have a idea?

### ISSUE THREAD

**Issue by willk24** [RandyGaul/cute_headers#121]
![image](https://user-images.githubusercontent.com/39808101/47809353-eede6d80-dd40-11e8-8e68-7566f215c187.png)

_Originally posted by @willk24 in https://github.com/RandyGaul/cute_headers/issues/120#issuecomment-434792765_

**Comment by RandyGaul** [comment]
Post up your json file, and I can try debugging it :)

**Comment by RandyGaul** [comment]
```cpp
cute_tiled_map_t* cute_tiled_load_map_from_file(const char* path, void* mem_ctx)
{
	int size;
	void* file = cute_tiled_read_file_to_memory_and_null_terminate(path, &size, mem_ctx);
	cute_tiled_map_t* map = cute_tiled_load_map_from_memory(file, size, mem_ctx);
	CUTE_TILED_FREE(file, mem_ctx);
	return map;
}

void test_map()
{
	cute_tiled_map_t* m = cute_tiled_load_map_from_file("map.json", 0);
	if (!m) return;
	print_map(m);
	cute_tiled_free_map(m);
}
```

This is the code I ran to open your file. It all looks OK to me. And here was the output:

`map :
        backgroundcolor : 0
        height : 20
        infinite : 0
        layer :
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                        data[i] : 7
                draworder.ptr : (null)
                height : 20
                name.ptr : Sol
                opacity : 1.000000
                properties :
                type.ptr : tilelayer
                visible : 1
                width : 20
                x : 0
                y : 0
        layer :
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 0
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                        data[i] : 2
                draworder.ptr : (null)
                height : 20
                name.ptr : Murs
                opacity : 1.000000
                properties :
                type.ptr : tilelayer
                visible : 1
                width : 20
                x : 0
                y : 0
        layer :
                draworder.ptr : topdown
                height : 0
                name.ptr : Murs
                object :
                        ellipse : 0
                        gid : 0
                        height : 144
                        id : 36
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 16
                        x : 80.000000
                        y : 160.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 320
                        id : 34
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 16
                        x : 0.000000
                        y : 0.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 32
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 144
                        x : 160.000000
                        y : 192.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 31
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 144
                        x : 160.000000
                        y : 240.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 30
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 144
                        x : 160.000000
                        y : 192.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 29
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 144
                        x : 160.000000
                        y : 192.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 28
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 64
                        x : 16.000000
                        y : 96.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 27
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 80
                        x : 16.000000
                        y : 48.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 26
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 80
                        x : 16.000000
                        y : 48.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 25
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 80
                        x : 224.000000
                        y : 80.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 24
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 80
                        x : 224.000000
                        y : 32.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 320
                        id : 22
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 16
                        x : 304.000000
                        y : 0.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 320
                        id : 21
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 16
                        x : 0.000000
                        y : 0.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 18
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 320
                        x : 0.000000
                        y : 304.000000
                object :
                        ellipse : 0
                        gid : 0
                        height : 16
                        id : 17
                        name.ptr :
                        point : 0
                        vertices :
                        vert_type : 0
                        properties :
                        rotation : 0.000000
                        type.ptr :
                        visible : 1
                        width : 320
                        x : 0.000000
                        y : 0.000000
                opacity : 1.000000
                properties :
                type.ptr : objectgroup
                visible : 1
                width : 0
                x : 0
                y : 0
        nextobjectid : 37
        orientation.ptr : orthogonal
        properties :
        renderorder.ptr : right-down
        tiledversion.ptr : 1.1.5
        tileheight : 16
        tileset :
                columns : 8
                firstgid : 1
                image.ptr : tileset.png
                imagewidth : 128
                imageheight : 32
                margin : 0
                name.ptr : tileset
                properties :
                spacing : 0
                tilecount : 16
                tileheight : 16
                tilewidth : 16
                type.ptr : (null)
                source.ptr : (null)
        tilewidth : 16
        type.ptr : map
        version : 1
        width : 20`

**Comment by willk24** [comment]
when i run this code : 

cute_tiled_map_t* map = cute_tiled_load_map_from_file("\Assets\Maps\map.json", 0);
if (!map) return;
cute_tiled_free_map(map);

it return nothing

**Comment by RandyGaul** [comment]
What compiler are you using? Are you sure you have the right directory? I think you'll have to use the debugger and step into the function to figure out what's going on.

**Comment by RandyGaul** [comment]
I added in a warning for unable to find file https://github.com/RandyGaul/cute_headers/commit/bcc8f215a4faf8ed12ed98875753fba4d260f63f

You can grab this version of cute_tiled.h, and it will print a warning for you if it's unable to find your file.

**Comment by willk24** [comment]
Now i got this in visual studio 2017

![image](https://user-images.githubusercontent.com/39808101/47818333-26a4df80-dd58-11e8-85e8-58475d2bb7a4.png)

**Comment by willk24** [comment]
And i put "map.json" in the origin folder so the directory wasn't wrong it's give me the same error

**Comment by RandyGaul** [comment]
Are you able to run the example code? I can’t help you any further since I don’t have enough information to see what’s happening.

**Comment by willk24** [comment]
I come back with more information

**Comment by willk24** [comment]
i got i work ! For now. I just had to put : 

cute_tiled_map_t* m = cute_tiled_load_map_from_file("map.json", 0);
if (!m) return;
std::cout << m->height << std::endl;
std::cout << m->tilesets->image.ptr << std::endl;
cute_tiled_free_map(m);

in a void and i can get all of the informations of the map

**Comment by willk24** [comment]
Thank you a lot for your help !

**Comment by RandyGaul** [comment]
Oh I see! You were looking at the map after freeing it?

Glad you got it working :)

Closing this for now, but feel free to reopen or make a new github issue if you need more help.
