### ISSUE TITLE
__debugbreak incompatible with GCC

### ISSUE THREAD

**Issue by legends2k** [RandyGaul/cute_headers#123]
As the headers (libraries) designed to be cross-platform, across toolchains, using `__debugbreak`, a MSVC compiler-only built-in, should be avoided; an equivalent macro that works across different tool chains might be a good middle ground.

**Comment by RandyGaul** [comment]
Which header? I meant to remove all these instances, but one may have slipped in.

**Comment by legends2k** [comment]
Silly me, forgot to mention.  This is in `cute_tiled.h`.

Off-hand, do you have any plans of upping the support to a newer version of Tiled?

**Comment by legends2k** [comment]
Closed _close and comment_ by mistake.

**Comment by RandyGaul** [comment]
This was fixed! Thanks for bringing it up :)
