### ISSUE TITLE
Why does cute_c2 capsule-to-capsule collision use GJK?

### ISSUE THREAD

**Issue by quadrupleslap** [RandyGaul/cute_headers#126]
It's probably a stupid question, but isn't the point of using capsules that you can just check the distance between the line segments?

**Comment by RandyGaul** [comment]
The code required to check the distance between two line segments will actually duplicate code inside of the GJK algorithm, albeit as a special case. GJK will actually be faster than computing the full closest points each frame assuming GJK is warm started with a cache.

**Comment by quadrupleslap** [comment]
> GJK will actually be faster than computing the full closest points each frame assuming GJK is warm started with a cache.

Thanks, that's pretty surprising.

**Comment by RandyGaul** [comment]
Yep, it’s going to be a negligible performance difference between special case code and GJK. So that means additional code duplication is not with it.
