### ISSUE TITLE
No licensing information in some headers

### ISSUE THREAD

**Issue by a-rodin** [RandyGaul/cute_headers#132]
In the beginning of [cute_font.h](https://github.com/RandyGaul/cute_headers/blob/master/cute_font.h) it is said that

> Licensing information can be found at the end of the file

but in fact there is no licensing information in the end of aforementioned fine.

The same is true for [cute_filewatch.h](https://github.com/RandyGaul/cute_headers/blob/master/cute_filewatch.h) and  [cute_coroutine.h](https://github.com/RandyGaul/cute_headers/blob/master/cute_coroutine.h).

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/commit/95683d6fc9674e42b8de44f2bda25dada675feab

Thanks for pointing that out! Was just an oversight :)
