### ISSUE TITLE
Suggestion for cute_spheremesh - Smooth Mesh Support

### ISSUE THREAD

**Issue by irlanrobson** [RandyGaul/cute_headers#134]
Hi Randy. 

I think it would be nice for an user to have a sphere mesh which contains a list of unique vertices and a list of triangle indices. It seems that you're duplicating vertices by simple adding each vertex of a subdivided edge to the mesh. Of course this is not a problem since the output is a list of triangle vertices.

Creating unique vertices can be done by keeping a map of subdivided edge to vertex. When you subdivide an edge you either add a new vertex or use a vertex from the map. More specifically if the opposite edge of an edge is on the map you use the associated vertex to create the new triangle. Otherwise you create a new vertex and add the edge-vertex pair to the map.

[Here](https://github.com/irlanrobson/bounce/blob/master/src/bounce/meshgen/sphere_mesh.cpp) is some working code to boost up implementation if you ever want to try this. 

HTH.

**Comment by RandyGaul** [comment]
Hi Irlan, thanks for the suggestion! It is a good suggestion. I’m not doing any sphere stuff lately so I wouldn’t be making this change until it became necessary. But if anyone posts up a PR I’ll gladly merge it in :)

**Comment by irlanrobson** [comment]
Just let you know I optimized the code above. Now it performs a single memory allocation. I also uses C-style notation. Maybe you can just implement your version based on this.

Note there might be a nice formula which gives the number of unique vertices in the final sphere mesh. I use the maximum number of vertices at the moment which works gracefully.

**Comment by RandyGaul** [comment]
The more optimized the more a pull request is appreciated :)

**Comment by RandyGaul** [comment]
Just pruning old issues
