### ISSUE TITLE
cute_png.h - weird sizeof expression

### ISSUE THREAD

**Issue by dkorpel** [RandyGaul/cute_headers#135]
While translating the cute_png header, I stumbled on this line:
```C
if (s) CUTE_PNG_MEMSET(s->lookup, 0, sizeof(512 * sizeof(uint32_t)));
```
https://github.com/RandyGaul/cute_headers/blob/master/cute_png.h#L376

It evaluates to `sizeof(512 * 4L)` -> `sizeof(long long)` -> `8`, but I don't get why only the first 8 bytes should be set to 0. If it is supposed to initialize the whole array, it should be `512 * sizeof(uint16_t)`, or better: 
`sizeof(s->lookup)`. 

What's the intention behind this expression?

**Comment by RandyGaul** [comment]
Oh that’s a typo. It’s supposed to clear the lookup table. That multiply should be outside the sizeof operator!
