### ISSUE TITLE
filewatch - can't watch more than one mount

### ISSUE THREAD

**Issue by ibachar** [RandyGaul/cute_headers#141]
Hi,

I tired using your library and noticed that you can't watch more than one mount directory. What was the reasoning behind it? I need assetsys to remount a folder when a file is added for it to know it exists and I'm using your library for it, but it seems it can't watch two different folders on the file system.

Thanks

**Comment by RandyGaul** [comment]
Do you mean one mount, or one directory?

The reason only one directory is watched was because the implementation polls naively, so polling subdirectories recursively is sort of complicated and wouldn't scale very well.

What specifically did you want to do that you can't?

**Comment by RandyGaul** [comment]
Hmm is it really true that more than one mount can not be watched? That sounds like a bug, since I don't remember this being an explicit limitation...

What is your current setup? I'm interested in hearing so I have reproduction steps.

**Comment by ibachar** [comment]
https://github.com/RandyGaul/cute_headers/blob/206f19adaea0af841b06a92ef1106efa5909c44f/cute_filewatch.h#L2072

I want to mount two different folders on disk to the same virtual path. This line seems to disallow it

**Comment by RandyGaul** [comment]
Oh gotcha! Yeah I'm not exactly sure what to do about this. The most straightforward solutions would just started duplicating code within assetsys. Thanks for posting about it here. I'll have to think about this some more.

**Comment by RandyGaul** [comment]
Ok I'm working on a solution. I think I came up with an easy way to add this feature and also fix this outstanding bug simultaneously https://github.com/RandyGaul/cute_headers/issues/106.

**Comment by RandyGaul** [comment]
Also I've actually switched to using Physics FS for my own game, and will likely port over cute_filewatch to also support [PhysicsFS](https://icculus.org/physfs/) eventually.

**Comment by RandyGaul** [comment]
Alrighty, try this out! There are a couple API breaking changes, but that's ok. I think the design of filewatch got a little stronger by adding `actual_path` to some of the functions.

Should support a couple new things.
1. More than one simultaneous filewatch mount is supported.
2. Different folders can be mounted to the same virtual path simultaneously.
3. Removing a mount does not remove any watches, except for one case. If the virtual mount was the last remaining mount for that specific virtual folder, all watches for the virtual folder will be stopped automatically (like reference counting for the virtual mount folder).
4. Calling `filewatch_stop_watching` will remove *all* watches on the virtual folder, even if various different actual folders were mounted to the virtual location.

If you find any other problems feel free to re-open this issue, or make a new one!

Thanks again for trying the library out. Have a nice weekend!
