### ISSUE TITLE
C2: Weird normals returned for c2RaytoAABB

### ISSUE THREAD

**Issue by martincohen** [RandyGaul/cute_headers#143]
Hello,

I have following test code that illustrates a bug I've found with `c2RaytoAABB` (or my lack of understanding of what `c2Raycast.n` is supposed to be):

```c
    {
        c2Ray A = {
            .p = { 99, -37.3501968f },
            .d = { 1, 0 },
            .t = 2.59959984f
        };
        c2AABB B = {
            .min = { 100, -64 },
            .max = { 110, 0 },
        };
        c2Raycast hit;
        ASSERT(c2RaytoAABB(A, B, &hit));
        ASSERT(hit.t == 1);
        ASSERT(hit.n.x == -1); // FAIL, n.x == 0
        ASSERT(hit.n.y == 0);  // FAIL, n.y == -1
    }
```

Following loop illustrates how the normal changes based on `c2Ray.p.y`:

```c
    for (int i = -63; i < 0; ++i) {
        c2Ray A = {
            .p = { 99, i },
            .d = { 1, 0 },
            .t = 2.59959984f
        };
        c2AABB B = {
            .min = { 100, -64 },
            .max = { 110, 0 },
        };
        c2Raycast hit;
        ASSERT(c2RaytoAABB(A, B, &hit));
        printf("%.2d %.1f %.1f\n", i, hit.n.x, hit.n.y);
    }
```

Output:

```
-63 0.0 -1.0
-62 0.0 -1.0
-61 0.0 -1.0
-60 0.0 -1.0
-59 0.0 -1.0
-58 0.0 -1.0
-57 0.0 -1.0
-56 0.0 -1.0
-55 0.0 -1.0
-54 0.0 -1.0
-53 0.0 -1.0
-52 0.0 -1.0
-51 0.0 -1.0
-50 0.0 -1.0
-49 0.0 -1.0
-48 0.0 -1.0
-47 0.0 -1.0
-46 0.0 -1.0
-45 0.0 -1.0
-44 0.0 -1.0
-43 0.0 -1.0
-42 0.0 -1.0
-41 0.0 -1.0
-40 0.0 -1.0
-39 0.0 -1.0
-38 0.0 -1.0
-37 0.0 -1.0
-36 -1.0 0.0
-35 -1.0 0.0
-34 -1.0 0.0
-33 -1.0 0.0
-32 -1.0 0.0
-31 -1.0 0.0
-30 -1.0 0.0
-29 -1.0 0.0
-28 -1.0 0.0
-27 0.0 1.0
-26 0.0 1.0
-25 0.0 1.0
-24 0.0 1.0
-23 0.0 1.0
-22 0.0 1.0
-21 0.0 1.0
-20 0.0 1.0
-19 0.0 1.0
-18 0.0 1.0
-17 0.0 1.0
-16 0.0 1.0
-15 0.0 1.0
-14 0.0 1.0
-13 0.0 1.0
-12 0.0 1.0
-11 0.0 1.0
-10 0.0 1.0
-09 0.0 1.0
-08 0.0 1.0
-07 0.0 1.0
-06 0.0 1.0
-05 0.0 1.0
-04 0.0 1.0
-03 0.0 1.0
-02 0.0 1.0
-01 0.0 1.0
```

**Comment by RandyGaul** [comment]
Great, thanks for posting. Let me put together a rendering of your test and see what is going on.

**Comment by martincohen** [comment]
Here's even simpler example, good sire. Also if the AABB is 10 high, the normals are consistent. Hopefully it'll help:

```c
    for (int i = 1; i < 30; ++i)
    {
        c2Ray A = {
            .p = { -1, i },
            .d = { 1, 0 },
            .t = 3
        };
        c2AABB B = {
            .min = { 0, 0 },
            .max = { 10, 30 },
        };
        c2Raycast hit = {0};
        ASSERT(c2RaytoAABB(A, B, &hit));
        printf("%.2d %.1f %.1f\n", i, hit.n.x, hit.n.y);
    }
```

**Comment by RandyGaul** [comment]
Got a repro. Should have a fix shortly.

![martin_cohen_ray_bug](https://user-images.githubusercontent.com/1919825/60376416-b1131100-99c3-11e9-9df5-cf5ffd1fa621.gif)

**Comment by martincohen** [comment]
You're the best!

Following most likely sucks, but works well for my axis-aligned rays as a temporary hot-fix (commented is the original code):
```c
int c2RaytoAABB(c2Ray A, c2AABB B, c2Raycast* out)
{
	c2v inv = c2V(1.0f / A.d.x, 1.0f / A.d.y);
	c2v d0 = c2Mulvv(c2Sub(B.min, A.p), inv);
	c2v d1 = c2Mulvv(c2Sub(B.max, A.p), inv);
	c2v v0 = c2Minv(d0, d1);
	c2v v1 = c2Maxv(d0, d1);
	float lo = c2Hmax(v0);
	float hi = c2Hmin(v1);

	if (hi >= 0 && hi >= lo && lo <= A.t)
	{
		// c2v c = c2Mulvs(c2Add(B.min, B.max), 0.5f);
		// c = c2Sub(c2Impact(A, lo), c);
		// c2v abs_c = c2Absv(c);
		// c2v abs_d = c2Absv(A.d);
		// if (abs_c.x > abs_c.y) out->n = c2V(c2Sign(c.x), 0);
		// else out->n = c2V(0, c2Sign(c.y));

		if (abs_d.x > abs_d.y) {
			out->n = c2V(-c2Sign(A.d.x), 0);
		} else {
			out->n = c2V(0, -c2Sign(A.d.y));
		}
		out->t = lo;
		return 1;
	}
	return 0;
}
```

**Comment by RandyGaul** [comment]
Got a fix! I'll post the details for anyone curious, and for myself to reference later.

The problem was I had tried to use a common raycast to aabb function used by the graphics community. It's good for getting a boolean result (yes/no), but left me in a terrible position to actually find the collision normal.

I went ahead and used the appropriate algorithm, the Separating Axis Test (SAT) before computing ray intersections. I mixed in deducing which face was hit with the time of impact calculations.

Barring any odd implementation bugs I might have missed, the algorithm itself should be numerically robust in all cases :)

Please let me know if you have any other problems! We can re-open this issue or start a new one as needed.

https://github.com/RandyGaul/cute_headers/commit/4cc6a3249128c0a6a72957e73708b35c70832fc3

**Comment by martincohen** [comment]
Thank you Randy a ton for fixing this so quickly.

I now have a whole bunch of new problems with my raycasting. I tracked it down to resulting `t` being "too precise" and had to decrease it by a `1e-2f` (smaller value might work too, didn't test). The variant before had the `t` working without the epsilon, so maybe guys adopting this new version should be informed.

**Comment by RandyGaul** [comment]
What was the epsilon for? I don’t quite understand. Could you please post up a sample code code to show your scenario?

**Comment by martincohen** [comment]
It's probably specific to the math I have in there, that I need to clean up. Don't worry about it & sorry for unrelated alarm. I'll open a new issue if I find something after I clean my code up.

Again thanks for the quick fix and amazing library, Randy. <3
