### ISSUE TITLE
cute_c2 : DLL export of implementation

### ISSUE THREAD

**Issue by Wizzard033** [RandyGaul/cute_headers#149]
As far as I can tell, there's no API define that I can change to export the library.

I've added one to cute_c2.h
```C
#if !defined(CUTE_C2_API)
#define CUTE_C2_API
#endif

// Just an example... I've prepended this to all function definitions
CUTE_C2_API int c2CircletoCircle(c2Circle A, c2Circle B);
````

I define CUTE_C2_API using `#define CUTE_C2_API extern "C" __declspec(dllexport)`

This was needed so that I can access the functions from the LuaJIT FFI

**Comment by Wizzard033** [comment]
A complete side note from the original topic: I also had to change C2_AABB to C2_TYPE_AABB because c2AABB already exists. The problem is that I parse out prefixes in my glue code automatically, and I cannot have 2 things that're named the same thing without the prefix. I'm not sure if this is something you'd want to fix, especially since it's an API-breaking change.

**Comment by RandyGaul** [comment]
These sound like great changes. If you make a pull request, I'll very likely just merge it in! Feel free to add yourself to the contributor list and make a note of your change. But be careful to preserve whitespace formatting of the documentation comments. I'm a stickler about the whitespace :)

Thanks for posting your improvements here!

**Comment by RandyGaul** [comment]
Oh also this would break my examples, but I can fix those myself, unless you feel up to also fix the examples while you're at it!

**Comment by RandyGaul** [comment]
Added your contribution to the docs https://github.com/RandyGaul/cute_headers/commit/bdf92bb7da9ae560615838bd33a1349783e1ce95

**Comment by Wizzard033** [comment]
That was fast. Thanks!
