### ISSUE TITLE
cute_sid.h [41]: SID macro incorrectly defines 'len' arg to sid_FNV1a

### ISSUE THREAD

**Issue by newparadime** [RandyGaul/cute_headers#157]
Line in question:
`#define SID(str, len) sid_FNV1a(str, str + strlen(str))
`

Function declaration of sid_FNV1a:
`uint64_t sid_FNV1a(const void* buf, int len);
`

Code snippet from definition of sid_FNV1a:
```
while (len--)
{
	char c = *str++;
	h = h ^ (uint64_t)c;
	h = h * (uint64_t)1099511628211;
}
```

If `len` equals  `str + strlen(str)`, then `while (len--)` would run for `<addr-of-str> + <length-of-str>` iterations. Since `str` is incremented every iteration of the while loop, the final value of `str` would be `<addr-of-str> + <addr-of-str> + <len-of-str>`. This doesn't seem correct, as it would overrun the end of the string by the number of bytes equal to the strings address (that's not what's intended, correct?). Am I missing something?

I propose that the macro `SID(str,len)` should be changed to the following:
`#define SID(str, len) sid_FNV1a(str, strlen(str))`

**Comment by RandyGaul** [comment]
It's a little confusing to follow exactly what you mean. Could you try making a pull-request? Then I can easily look at the diff and see what change you are proposing.

I'm sure you're correct, it's just a little hard to understand right here.

**Comment by RandyGaul** [comment]
Feel free to re-open this if you like! I'm just closing this to prune out old github issues.
