### ISSUE TITLE
c2RayToCapsule giving weird results

### ISSUE THREAD

**Issue by TylerGlaiel** [RandyGaul/cute_headers#159]
see gif

![raytocapsule](https://user-images.githubusercontent.com/1686664/68081094-81d33d00-fdc5-11e9-968c-6fd9ea419666.gif)

**Comment by RandyGaul** [comment]
This might have been a regression somehow. Hmm. I'll investigate this soon, likely this weekend.

**Comment by RandyGaul** [comment]
Was fairly easy to repro. Working on fixes now.

**Comment by RandyGaul** [comment]
Should be fixed here https://github.com/RandyGaul/cute_headers/commit/cc5f42b5b80e7aefbec239bf27a7f5b2c0ceab85

Feel free to re-open if you still have problems.

If the ray starts within the capsule there will not be a particularly useful normal.
