### ISSUE TITLE
cute_c2 Basic Collision Test Is Incorrect

### ISSUE THREAD

**Issue by PDeveloper** [RandyGaul/cute_headers#160]
The following code outputs "POLYGONS ARE ***NOT*** COLLIDING" even though if you plot the 2 rectangles, they are clearly intersecting.

```c++
{
	c2v p0[] = {
		{ -568.0f, 928.0f },
		{ -568.0f, 1056.0f },
		{ -848.0f, 1056.0f },
		{ -848.0f, 928.0f }
	};
	c2v p1[] = {
		{ -688.0f, 736.0f },
		{ -688.0f, 1184.0f },
		{ -912.0f, 1184.0f },
		{ -912.0f, 736.0f }
	};

	c2Poly poly0;
	c2Poly poly1;

	poly0.count = poly1.count = 4;

	memcpy_s(poly0.verts, 8 * sizeof(c2v), p0, 4 * sizeof(glm::vec2));
	c2MakePoly(&poly0);

	memcpy_s(poly1.verts, 8 * sizeof(c2v), p1, 4 * sizeof(glm::vec2));
	c2MakePoly(&poly1);

	if (c2PolytoPoly(&poly0, nullptr, &poly1, nullptr))
	{
		printf("POLYGONS ARE COLLIDING\n");
	}
	else
	{
		printf("POLYGONS ARE ***NOT*** COLLIDING\n");
	}
}
```

EDIT:
Note, this applies to v1.04 as well as the current v1.07

**Comment by RandyGaul** [comment]
Thanks for writing down a test! I'll be looking into cute_c2 again soon. Your test should make it pretty easy to see what's going on.

**Comment by RandyGaul** [comment]
Ah, you're using huge shapes which is hitting the precision limits inside of the `c2GJK` function internally.

You have two options.

1. Use a dedicated AABB to AABB function, which won't have these numeric problems for any sized shapes.
2. Dramatically scale your shapes down and transform them to the origin before applying any collision detection. This will heavily reduce the magnitude of intermediary area values calculated by `c2GJK`.

I'm going to close this out, but feel free to keep commenting if you have more questions or anything :)

**Comment by RandyGaul** [comment]
Just a quick note -- this topic actually helped a lot! It wasn't merely closed. The suggestions here were incorporated into the documentation of cute_c2. If anyone happens by here and reads this later on, please do open topics to ask questions like these! It's very helpful.
