### ISSUE TITLE
cute_spritebatch.h build error/warning

### ISSUE THREAD

**Issue by Clownacy** [RandyGaul/cute_headers#168]
Compiling with Clang 9.0.1, I get a warning about this line in `spritebatch_internal_get_pixels`:
```c
	memset(sb->pixel_buffer, size, 0);
```
The last two parameters are in the wrong order.

I also get an error about `spritebatch_best_fit` using INT_MAX, which is defined in `limits.h`, but that header is never included.

**Comment by RandyGaul** [comment]
Thank you! Will take a look soon :)

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/commit/6fea505e621eb0495fe587ce3d9ab2f21c7a5788
