### ISSUE TITLE
cute_sound: Buffer size minimum of 8192?

### ISSUE THREAD

**Issue by metasprite** [RandyGaul/cute_headers#169]
That's 180ms of audio latency at 44.1khz, I was able to notice such a delay immediately. Luckily I only needed to change a few lines to remove the minimum, and everything seems to work fine. Is there a reason it was there in the first place (and without any notes about its existence)?

**Comment by RandyGaul** [comment]
Could you link to line numbers so I know for sure which thing you’re talking about? Thank you! :)

**Comment by metasprite** [comment]
https://github.com/RandyGaul/cute_headers/blob/master/cute_sound.h#L1110
https://github.com/RandyGaul/cute_headers/blob/master/cute_sound.h#L1311
https://github.com/RandyGaul/cute_headers/blob/master/cute_sound.h#L1572
https://github.com/RandyGaul/cute_headers/blob/master/cute_sound.h#L1783

**Comment by RandyGaul** [comment]
Ah! That was a very recent change. I was trying to simplify the function to construct a cute sound context. During testing I noticed that a really small buffer seems to work just fine, but I picked a larger one simply to be conservative. I wasn't exactly sure what to pick.

Here is a good modification we can make to cute sound:

```cpp
#ifndef CUTE_SOUND_MINIMUM_BUFFERED_SAMPLES
#	define CUTE_SOUND_MINIMUM_BUFFERED_SAMPLES 1024
#endif
```

**Comment by RandyGaul** [comment]
Feel free to re-open if needed :)
