### ISSUE TITLE
cute_sound.h - confusing SDL docs.

### ISSUE THREAD

**Issue by swifton** [RandyGaul/cute_headers#171]
It says

"SDL is used for all other platforms. Define CUTE_SOUND_FORCE_SDL before placaing the CUTE_SOUND_IMPLEMENTATION in order to force the use of SDL."

So I thought that SDL will be used on Windows by default, and you can also force it on Apple and Linux if you want. In reality, it is unclear what is used on Windows by default, but it's not SDL. If you don't define CUTE_SOUND_FORCE_SDL, there will be no sound.

**Comment by RandyGaul** [comment]
I can see how this might be confusing. I'll try rewriting it.

https://github.com/RandyGaul/cute_headers/blob/master/cute_sound.h

Let me know if anything is still confusing!
