### ISSUE TITLE
cute_sound.h shuts down if you play too many sounds.

### ISSUE THREAD

**Issue by swifton** [RandyGaul/cute_headers#172]
If you try to play more sounds than you created pools for, cute_sound will stop playing any sounds at all. This could be handled better by dropping the oldest sound, for example. Or dropping the sound that is the closest to finishing and writing an error to cs_error_reason.

**Comment by RandyGaul** [comment]
I'm actually thinking to just assert when this happens -- let me check the code real quick to see what's going on...

**Comment by RandyGaul** [comment]
Assuming you're using `cs_play_sound`, it shouldn't stop playing any sounds, it should simply return `NULL` in this case.

https://github.com/RandyGaul/cute_headers/blob/master/cute_sound.h#L2043-L2048

Are you checking this return value?

**Comment by RandyGaul** [comment]
Found the bug after testing it https://github.com/RandyGaul/cute_headers/commit/befe4a21a0fda73efa2623bef12d7a3c572f6481

Here's my test program:

```
#define CUTE_SOUND_IMPLEMENTATION
#include "cute_sound.h"

#include <stdio.h>

int main()
{
	HWND hwnd = GetConsoleWindow();
	cs_context_t* ctx = cs_make_context(hwnd, 44100, 1024 * 8, 2, NULL);
	cs_loaded_sound_t select_audio = cs_load_wav("select.wav");
	cs_play_sound_def_t def = cs_make_def(&select_audio);
	printf("select.wav has a sample rate of %d Hz.\n", select_audio.sample_rate);

	printf("Press the 1 key!\n");
	printf("Press ESC to exit.\n");

	cs_spawn_mix_thread(ctx);

	while (1)
	{
		if (GetAsyncKeyState(VK_ESCAPE)) {
			break;
		}

		if (GetAsyncKeyState(0x31)) {
			cs_play_sound(ctx, def);
		}

		Sleep(100);
	}

	cs_free_sound(&select_audio);
}
```
