### ISSUE TITLE
cute_sound.h docs out of date.

### ISSUE THREAD

**Issue by swifton** [RandyGaul/cute_headers#173]
The high level API section says:

cs_context_t* ctx = cs_make_context(hwnd, frequency, latency, seconds, N);

The low level API section says:

cs_context_t* ctx = cs_make_context(hwnd, frequency, buffered_samples, 0);

This function seems to have other parameters now.

**Comment by RandyGaul** [comment]
Let me know if you spot other problems!

https://github.com/RandyGaul/cute_headers/commit/e530a1071ad2b8a49aad1456e1e4875d71f4da32
