### ISSUE TITLE
sound positon

### ISSUE THREAD

**Issue by codz01** [RandyGaul/cute_headers#176]
Hi RandyGaul
is it possible to get/set the current position of playing sound ?

**Comment by RandyGaul** [comment]
You can set `sample_index` in a playing sound instance. However, be careful if you're running the mixer on a separate thread, or if you called `cs_spawn_mix_thread` to mix on another thread. Simply writing to `sample_index` in this case will cause a race condition.

**Comment by codz01** [comment]
thank you very much

**Comment by codz01** [comment]
hi agin :)
how i can get playing time (seconds) using sample index ?

**Comment by RandyGaul** [comment]
The frequency parameter you pass into the context creation function can be used. Frequency is samples / seconds, so to get seconds divide the sample index by frequency.

(1 sample / 1) * (seconds / samples) = sample_index / (double)frequency

**Comment by codz01** [comment]
oh that was simple how i couldn't discover it :/
thank you for these nice headers :)
