### ISSUE TITLE
cute_spritebatch.h: Failure to compile on FreeBSD

### ISSUE THREAD

**Issue by GabrielRavier** [RandyGaul/cute_headers#179]
On FreeBSD, including `cute_spritebatch.h` fails with this error : 
`cute_spritebatch.h:472:12: fatal error: 'alloca.h' file not found`

`SPRITEBATCH_ALLOCA` seems to be used nowhere, so the temporary fix would be to `#define SPRITEBATCH_ALLOCA` before including `cute_spritebatch.h`. 
A simple solution would be to remove this macro entirely.

If you want to use `alloca` in the future, I'd recommand including `alloca` via the `stdlib.h` header on FreeBSD (detect it via `__FreeBSD__`), or just using `stdlib.h` in general for this, which works on (at least) Linux, OpenBSD, MacOS.

**Comment by RandyGaul** [comment]
Huh interesting, if I'm remembering correctly that didn't work on Windows.

If you're up for it, please do put in a pull request! Maybe using __FreeBSD__ and swap the include file to stdlib.h. I'd happily add you to the contributor list.

**Comment by GabrielRavier** [comment]
I mean, personally I'd just remove the macro, considering it's unused, but I'll make a PR with a FreeBSD fix

**Comment by RandyGaul** [comment]
Ah I misunderstood, removing it is just fine as well :)
