### ISSUE TITLE
cute_sound.h: SIMD undesirable with Emscripten

### ISSUE THREAD

**Issue by fluffrabbit** [RandyGaul/cute_headers#184]
One advantage that Emscripten has over other WebAssembly compilers such as the WASM backend being added to GCC is that Emscripten can output JavaScript instead of WASM, for compatibility with older browsers. JavaScript has no SIMD intrinsics.

When adding the Bullet physics engine to my game, I had to disable SIMD for the Emscripten build due to crazy bugs like the player's capsule collider turning on its side. Bullet's performance is perfectly acceptable without SIMD. Unfortunately, cute_sound always uses intrinsics, and you can't turn that behavior off. If the build system lacks SIMD headers, too bad. If you just want to avoid the potential bugs, too bad.

I'm wondering what it would take to add a non-SIMD mode to cute_sound. I don't know the fundamentals of SSE, so I have trouble reading those parts of the code. However, I know what I'm doing enough that I could probably replace those parts with their non-SIMD counterparts without bloating the code too much. Any thoughts on this that might help?

**Comment by RandyGaul** [comment]
You don't need to convince me Emscripten is cool :) It's quite easy to remove the SIMD. The overall algorithm is:

1. Take two int16 arrays (the source audio)
2. Convert the samples to float
3. Add the samples together
4. Finally, convert the float samples back to int16

`__m128` is four floats, `__m128i` is four ints.

My recommendation is to simply find all the `_mm_***` functions and implement scalar mode for them. Here is an example of a couple, and also define `__m128` and `__m128i` somewhere. You can even hide the `__m128` inside of a `cs_128_float` type if you like. There are many options.

```cpp
struct cs_128_float
{
	float a, b, c, d;
};

__m128 _mm_mul_ps(__m128 a, __m128 b)
{
	__m128 c;
	c.a = a.a * b.a;
	c.b = a.b * b.b;
	c.c = a.c * b.c;
	c.d = a.d * b.d;
	return c;
}
```

You can look up any of the SIMD functions here https://software.intel.com/sites/landingpage/IntrinsicsGuide/

There's even scalar psuedo code that's almost copy pastable into scalar functions. Here's my own description of the slightly complicated instrinsics. I can help you write scalar version of these if needed, just ask.

* _mm_cvtps_epi32 - convert float to 32 bit int
* _mm_unpacklo_epi32 - unpack the first two integers of parameters a and b into interleaved form
* _mm_unpackhi_epi32 - unpack the third and fourth integers of parameters a and b into interleaved form
* _mm_packs_epi32 - pack all 8 integers from parameters a and b into signed 16 bit integers in interleaved form

Interleaved simply means if we take samples from two sources and fill a destination array, the destination array has one sample from the first source, followed by a sample from the second source, and then a sample from the first source, and so on back and forth.

**Comment by fluffrabbit** [comment]
I missed you, buddy! Yeah, I felt that I had to leave TIG on account of the "games as art" people flooding the place with their throwaway projects. The time investment in my project so far doesn't make me feel comfortable screwing around.

I will reach out on individual points when I need help. You mention converting the samples to float before adding them. I know there's stuff like multiplication in there as well, but wouldn't adding floats and converting them back to ints be the same as adding ints?

**Comment by fluffrabbit** [comment]
Here's what I have so far:

```c
#ifdef CUTE_SOUND_SCALAR_MODE

	typedef struct __m128
	{
		float a, b, c, d;
	} __m128;

	__m128 _mm_set_ps(float e3, float e2, float e1, float e0)
	{
		__m128 a;
		a.a = e0;
		a.b = e1;
		a.c = e2;
		a.d = e3;
		return a;
	}

	__m128 _mm_mul_ps(__m128 a, __m128 b)
	{
		__m128 c;
		c.a = a.a * b.a;
		c.b = a.b * b.b;
		c.c = a.c * b.c;
		c.d = a.d * b.d;
		return c;
	}

#else

	#include <xmmintrin.h>
	#include <emmintrin.h>

#endif // CUTE_SOUND_SCALAR_MODE
```

When I try to compile, Clang gives me: `fatal error: definition of type '__m128' conflicts with typedef of the same name`

Apparently, `xmmintrin.h` is included automatically by other headers in some build systems. `#define`/`#undef` doesn't seem to work for `__m128`, so should I replace all occurrences of `__m128` with `cs__m128` or something? I think the approach of replacing SIMD keywords with `cs`-prefixed versions where conflicts arise would be a good approach.

**Comment by RandyGaul** [comment]
Multiplying integers is not quite the same since adding two signed 16-bit integers can overflow pretty easily, but as a float the chance of overflow is very slim.

The mix buffer starts as all zeroes, and each playing audio instance adds its samples. Since the numbers are signed and fairly random with respect to one another, the audio mostly stays somewhere within the signed 16-bit range without overflowing. However, it's more likely for the individual addition operations to overflow somewhere during the mixing stage, as compared to the likelihood of the final result overflowing. That's why floats are used during the mixing stage.

Using a wrapper type like `cs_m128` is a good idea.

**Comment by fluffrabbit** [comment]
>Multiplying integers is not quite the same since adding two signed 16-bit integers can overflow pretty easily, but as a float the chance of overflow is very slim.

I didn't think about overflows. There would inevitably be clipping unless `s16_le` audio is on a logarithmic scale or something (I doubt it). I guess when you cast a big float to an int16 it just clips?

>Using a wrapper type like `cs_m128` is a good idea

Great! Note the two underscores for consistency with the official API.

**Comment by RandyGaul** [comment]
> I didn't think about overflows. There would inevitably be clipping unless s16_le audio is on a logarithmic scale or something (I doubt it). I guess when you cast a big float to an int16 it just clips?

Right, it's just a cast, so you'll still get truncation. Say we have a few samples, 60, 30, -50, and -20, and if any value is over 63 (or -64) then there is an overflow/underflow. If the mix buffer were in integral form, adding 0 and 60 is fine. But adding 60 to 30 overflows. Similarly, adding -50 and -20 underflows. But if we mix in float form, the sum is 20, and doesn't overflow or underflow when cast back to int.

Having a single cast at the end is much less likely to clip.

**Comment by fluffrabbit** [comment]
I'm a bit thrown by `_mm_set_ps` going in reverse order. Is this correct:

```c
	cs__m128 cs_mm_load_ps(float const* mem_addr)
	{
		cs__m128 a;
		a.a = mem_addr[0];
		a.b = mem_addr[1];
		a.c = mem_addr[2];
		a.d = mem_addr[3];
		return a;
	}
```

**Comment by RandyGaul** [comment]
Looks backwards, but you can double check with the debugger on Windows.

**Comment by fluffrabbit** [comment]
I don't have Windows or MSVC, but I'll take your word for it.

**Comment by RandyGaul** [comment]
Ah, you meant _mm_load_ps not _mm_set_ps, yes that looks correct.

**Comment by fluffrabbit** [comment]
What I mean is when you look at this prototype: `cs__m128 cs_mm_set_ps(float e3, float e2, float e1, float e0)` you see it starts with e3 and ends with e0, and the assignment goes e0...e3 in destination memory. `float const* mem_addr` is just a pointer, and I'm guessing just a copier.

**Comment by RandyGaul** [comment]
Yeah you got it, here's the thingy from the intel docs:

dst[127:0] := MEM[mem_addr+127:mem_addr]

So that's like a for loop like so:

```
for (int i = 0; i < 4; ++i) dst = src[i]
```

Their notation is dumb, but sort of understandable.

**Comment by RandyGaul** [comment]
I think the reason that _mm_set_ps goes from 3 to 0 is most of their notation starts from the high index and goes to the low index. I have no idea why, and honestly it's annoying.

**Comment by fluffrabbit** [comment]
>Their notation is dumb, but sort of understandable.

Understandable how?

`dst[127:0] := MEM[mem_addr+127:mem_addr]`

Sorry, what?

**Comment by RandyGaul** [comment]
It means bit index 0 through 127, but they reverse notation to show 127 through 0.

**Comment by fluffrabbit** [comment]
Hmm. What's a good approach to `_mm_packs_epi32` that avoids endianness issues? I could use a bit mask with `0x`whatever, but that's endian-dependent. Would you cast a struct of `{int16_t, int16_t}` to `int32_t`, and would `#pragma pack` help?

**Comment by RandyGaul** [comment]
Don't worry about endianness issues. If you use bitmasks and shift operators the compiler will figure out endianness for you. The only time endianness will be a problem is if a machine writes bytes and those bytes are literally copied to another machine with different endian ordering. That can not happen with cute sound.

Here's an example about endianness independence https://github.com/r-lyeh/tinybits/issues/3

**Comment by fluffrabbit** [comment]
Thanka, I'll sleep on it.

**Comment by RandyGaul** [comment]
More information: https://stackoverflow.com/questions/56385192/is-reading-one-byte-at-a-time-endianness-agnostic-regardless-of-value-size

**Comment by fluffrabbit** [comment]
It's too much code and difficult to figure out. Surely there's a simpler solution. I'll have to think on it.

**Comment by RandyGaul** [comment]
It's only 6 lines of code?

Though another valid solution is to simply not worry about endianness at all and just stick to your saturate macros. People using SSE intrinsics will be on an Intel chip anyways, which is little endian. It's pretty much not possible for endian issues to pop up at all.

It's up to you! I'm happy with any of these options.

**Comment by fluffrabbit** [comment]
People **not** using SSE intrinsics with be using this mode. I'm just not sure about adding `cs_write_uint16`, especially since my reptile brain is having trouble coming to grips with what it does.

**Comment by RandyGaul** [comment]
Here's a simpler version. It doesn't move the `p` pointer. Mask off the first half of `value`, write it, then shift it away to get the second half. The other version I posted is a little fancier and also moves the `p` pointer forward by two bytes.

```cpp
void cs_write_uint16(uint8_t* p, uint16_t value)
{
	p[0] = value & 0xFF; // First 8 bits
	p[1] = value >> 8;   // Second 8 bits
}
```

**Comment by fluffrabbit** [comment]
Why `uint16_t` rather than `int16_t`?

**Comment by RandyGaul** [comment]
No reason :)

**Comment by fluffrabbit** [comment]
I hate bitwise stuff because there's so much room for UB and compiler errors. I'm sorry, I got a slow start this morning.

**Comment by fluffrabbit** [comment]
Not only does this not compile, I also think there is a local fallacy in the second function:

```c
	void cs_write_int16(uint8_t* p, int16_t value)
	{
		p[0] = value & 0xFF; // First 8 bits
		p[1] = value >> 8;   // Second 8 bits
	}

	cs__m128i cs_mm_packs_epi32(cs__m128i a, cs__m128i b)
	{
		int16_t c[8];
		int16_t* p = c;
		cs_write_int16(&p, CS_SATURATE16(a.a));
		cs_write_int16(&p, CS_SATURATE16(a.b));
		cs_write_int16(&p, CS_SATURATE16(a.c));
		cs_write_int16(&p, CS_SATURATE16(a.d));
		cs_write_int16(&p, CS_SATURATE16(b.a));
		cs_write_int16(&p, CS_SATURATE16(b.b));
		cs_write_int16(&p, CS_SATURATE16(b.c));
		cs_write_int16(&p, CS_SATURATE16(b.d));
		return *(cs__m128i*)c;
	}
```

Also, I'm sure there will be strict aliasing warnings when it does work. This whole thing gives me a headache. Element padding is out of control in C, probably to satisfy the needs of different hardware vendors. So no amorphous memory blocks, and a union is not the way due to the complexity it adds. I honestly don't have a clue how to proceed.

**Comment by RandyGaul** [comment]
```cpp
#include <stdint.h>
#include <limits.h>
#include <stdio.h>

typedef struct cs__m128
{
	float a, b, c, d;
} cs__m128;

typedef struct cs__m128i
{
	int a, b, c, d;
} cs__m128i;

void cs_write_int16(uint8_t** p, uint16_t value)
{
	(*p)[0] = value & 0xFF;
	(*p)[1] = value >> 8;
	*p += 2;
}

#define CS_SATURATE16(X) (int16_t)(X > SHRT_MAX ? SHRT_MAX : (X < SHRT_MIN ? SHRT_MIN : X))

cs__m128i cs_mm_packs_epi32(cs__m128i a, cs__m128i b)
{
	int16_t c[8];
	uint8_t* p = (uint8_t*)&c;
	cs_write_int16(&p, CS_SATURATE16(a.a));
	cs_write_int16(&p, CS_SATURATE16(a.b));
	cs_write_int16(&p, CS_SATURATE16(a.c));
	cs_write_int16(&p, CS_SATURATE16(a.d));
	cs_write_int16(&p, CS_SATURATE16(b.a));
	cs_write_int16(&p, CS_SATURATE16(b.b));
	cs_write_int16(&p, CS_SATURATE16(b.c));
	cs_write_int16(&p, CS_SATURATE16(b.d));
	return *(cs__m128i*)c;
}

int main()
{
	cs__m128i a;
	a.a = 1;
	a.b = 2;
	a.c = 4;
	a.d = 8;

	cs__m128i b = cs_mm_packs_epi32(a, a);

	printf("%d\n", b.a & 0xFF);
	printf("%d\n", b.a >> 16);
	printf("%d\n", b.b & 0xFF);
	printf("%d\n", b.b >> 16);
	printf("%d\n", b.c & 0xFF);
	printf("%d\n", b.c >> 16);
	printf("%d\n", b.d & 0xFF);
	printf("%d\n", b.d >> 16);

	return 0;
}
```

Outputs this

```
1
2
4
8
1
2
4
8
```

Compiles cleanly on Windows and with gcc -Wall -Wextra -pedantic.

**Comment by fluffrabbit** [comment]
That code snippet compiles without warnings, but when I adjust the code in cute_sound.h, it says:

` warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]`

Weird.

**Comment by RandyGaul** [comment]
What line number? Post the problem code and we can fix it.

**Comment by fluffrabbit** [comment]
Scratch that, I only get the warning when compiling it in certain projects, but on its own, nothing. It was the part where you `return *(cs__m128i*)c;`. False alarm maybe. There also unrelated warnings with Clang. Hmm.

**Comment by RandyGaul** [comment]
This should avoid type punning.

```cpp
#include <stdint.h>
#include <limits.h>
#include <stdio.h>

typedef struct cs__m128
{
	float a, b, c, d;
} cs__m128;

typedef struct cs__m128i
{
	int a, b, c, d;
} cs__m128i;

void cs_write_int16(uint8_t** p, int16_t value)
{
	(*p)[0] = value & 0xFF;
	(*p)[1] = value >> 8;
	*p += 2;
}

#define CS_SATURATE16(X) (int16_t)(X > SHRT_MAX ? SHRT_MAX : (X < SHRT_MIN ? SHRT_MIN : X))

cs__m128i cs_mm_packs_epi32(cs__m128i a, cs__m128i b)
{
	union {
		int16_t c[8];
		cs__m128i m;
	} no_type_punning;
	uint8_t* p = (uint8_t*)no_type_punning.c;
	cs_write_int16(&p, CS_SATURATE16(a.a));
	cs_write_int16(&p, CS_SATURATE16(a.b));
	cs_write_int16(&p, CS_SATURATE16(a.c));
	cs_write_int16(&p, CS_SATURATE16(a.d));
	cs_write_int16(&p, CS_SATURATE16(b.a));
	cs_write_int16(&p, CS_SATURATE16(b.b));
	cs_write_int16(&p, CS_SATURATE16(b.c));
	cs_write_int16(&p, CS_SATURATE16(b.d));
	return no_type_punning.m;
}

int main()
{
	cs__m128i a;
	a.a = 1;
	a.b = 2;
	a.c = 4;
	a.d = 8;

	cs__m128i b = cs_mm_packs_epi32(a, a);

	printf("%d\n", b.a & 0xFF);
	printf("%d\n", b.a >> 16);
	printf("%d\n", b.b & 0xFF);
	printf("%d\n", b.b >> 16);
	printf("%d\n", b.c & 0xFF);
	printf("%d\n", b.c >> 16);
	printf("%d\n", b.d & 0xFF);
	printf("%d\n", b.d >> 16);

	return 0;
}
```

**Comment by fluffrabbit** [comment]
If we're using unions, how about this:

```c
	cs__m128i cs_mm_packs_epi32(cs__m128i a, cs__m128i b)
	{
		union {
			int16_t c[8];
			cs__m128i m;
		} dst;
		dst.c[0] = CS_SATURATE16(a.a);
		dst.c[1] = CS_SATURATE16(a.b);
		dst.c[2] = CS_SATURATE16(a.c);
		dst.c[3] = CS_SATURATE16(a.d);
		dst.c[4] = CS_SATURATE16(b.a);
		dst.c[5] = CS_SATURATE16(b.b);
		dst.c[6] = CS_SATURATE16(b.c);
		dst.c[7] = CS_SATURATE16(b.d);
		return dst.m;
	}
```

No warnings with g++.

**Comment by fluffrabbit** [comment]
It's now ready for a PR, but unfortunately I keep bumping up against this unrelated warning in Clang:

```
include/cute_sound.h:794:2: warning: indirection of non-volatile null pointer will be deleted, not trap [-Wnull-dereference]
        CUTE_SOUND_ASSERT(!((size_t)p & 15));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/cute_sound.h:746:45: note: expanded from macro 'CUTE_SOUND_ASSERT'
#define CUTE_SOUND_ASSERT(X) do { if (!(X)) CUTE_SOUND_ASSERT_INTERNAL; } while (0)
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
include/cute_sound.h:744:37: note: expanded from macro 'CUTE_SOUND_ASSERT_INTERNAL'
        #define CUTE_SOUND_ASSERT_INTERNAL *(int*)0 = 0
                                           ^~~~~~~~
include/cute_sound.h:794:2: note: consider using __builtin_trap() or qualifying pointer with 'volatile'
include/cute_sound.h:746:45: note: expanded from macro 'CUTE_SOUND_ASSERT'
#define CUTE_SOUND_ASSERT(X) do { if (!(X)) CUTE_SOUND_ASSERT_INTERNAL; } while (0)
                                            ^
include/cute_sound.h:744:37: note: expanded from macro 'CUTE_SOUND_ASSERT_INTERNAL'
        #define CUTE_SOUND_ASSERT_INTERNAL *(int*)0 = 0
```

etc. I don't have a clue what it's talking about. Should we PR first and address this later?

**Comment by RandyGaul** [comment]
It just wants to use `__builtin_trap` for `CUTE_SOUND_ASSERT`, you can detect this with `__clang__`.

```cpp
#ifdef __clang__
	#define CUTE_SOUND_ASSERT __builtin_trap
#else
	#define CUTE_SOUND_ASSERT *((int*)0) = 0
#endif
```

**Comment by RandyGaul** [comment]
Ah looks like `#if CUTE_SOUND_PLATFORM == CUTE_SOUND_APPLE && defined(__clang__)` might need to be changed to `||` instead of `&&`, or just remove the apple check.

**Comment by fluffrabbit** [comment]
I removed the Apple check. The compilers are presumably set up the same way across Unixes.
