### ISSUE TITLE
cute_tiled.h: Skipped property type will read some float values as int

### ISSUE THREAD

**Issue by aganm** [RandyGaul/cute_headers#188]
I have created a float property in the tiled editor. When the value has decimals, it is saved as expected (1.5 saved as "float": "1.5"), and it is parsed by cute_tiled as a float. But if the value doesn't have decimals, tiled saves this value as an integer (2.0 saved as "float": "2"), and cute_tiled parses it as in integer.

When trying to read the value from cute_tiled, I was expecting the type of the value to be float because I said it was float in tiled editor until I find out cute_tiled deduces the type from the value string and ignores the assigned type. (cute_tiled.h:1640)

If I want to find a float property from cute_tiled, I have to check for both CUTE_TILED_PROPERTY_INT and CUTE_TILED_PROPERTY_FLOAT.

What do you think of changing cute_tiled so that it parses property values according to the type?

**Comment by aganm** [comment]
I added a first solution in #189.  A special case that uses the type to make a float property without decimals be parsed as float instead of int.

**Comment by aganm** [comment]
Also I see potential for optimization there. Instead of parsing the types, there could be a simple switch on the type from the JSON.

```
switch(type_char)
{
case 'b': // bool
        cute_tiled_read_bool(m, &prop.data.boolean);
        prop.type = CUTE_TILED_PROPERTY_BOOL;
        break;
case 's': // string
        ...
        break;
case 'h': // hex
        ...
        break;
case 'f': // float
        ...
        break;
case 'i': // int
        ...
        break;
}
```

**Comment by RandyGaul** [comment]
Ah, this makes a bit more sense. Please stick with the old parser, but simply convert the type based on the type_char. This will reduce amount of code that needs to change and greatly reduce the risk of introducing new bugs. Converting between float, int, and bool should be quite trivial since it’s just a union and a type enum.

**Comment by RandyGaul** [comment]
Went ahead and merged in your changes. Nice edits! Good quality pull request. Feel free to close this out or comment here more if needed :)
