### ISSUE TITLE
cute_tiled: wrong type for object width/height

### ISSUE THREAD

**Issue by bjorn** [RandyGaul/cute_headers#204]
Currently objects width and height are stored and read as int (`cute_tiled_read_int(m, &object->width);`), but like the object position, those values should really be read as floats. This is causing problems when loading maps with objects that have non-integer sizes.

**Comment by RandyGaul** [comment]
Do you recommend making the width/height a float instead of an int, and not only parsing them as floats?

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/commit/9dc43d789f2256bd72ed55c36016de5f1490bcfd

**Comment by bjorn** [comment]
The way you fixed it seems fine. :-)
