### ISSUE TITLE
cute_sound.h: mem_ctx is missing from APPLE version of struct cs_context_t

### ISSUE THREAD

**Issue by andykt** [RandyGaul/cute_headers#211]
I needed to add "void* mem_ctx;" to the struct cs_context_t if CUTE_SOUND_PLATFORM == CUTE_SOUND_APPLE.

It would be nice to see some simple macOS examples.  Towards that end here's a Makefile and hello.c that work on macOS 10.15.

------------- Makefile --------------
hello : hello.c
	gcc -I../../ hello.c -o $@ -framework AudioToolbox -framework CoreGraphics

------------- hello.c ----------------
// create header + implementation
#define CUTE_SOUND_IMPLEMENTATION
#include "cute_sound.h"

#include <CoreGraphics/CoreGraphics.h>
#include <stdio.h>

int main()
{
	cs_context_t* ctx = cs_make_context(0, 44100, 8192, 0, NULL);
	cs_loaded_sound_t jump_audio = cs_load_wav("../jump.wav");
	cs_loaded_sound_t select_audio = cs_load_wav("select.wav");
	cs_playing_sound_t jump_instance = cs_make_playing_sound(&jump_audio);
	cs_playing_sound_t select_instance = cs_make_playing_sound(&select_audio);
	printf("jump.wav has a sample rate of %d Hz.\n", jump_audio.sample_rate);
	printf("select.wav has a sample rate of %d Hz.\n", select_audio.sample_rate);

	printf("Press the shift or option keys!\n");
	printf("Press ESC to exit.\n");

	while (1)
	{
	    if (CGEventSourceKeyState(kCGEventSourceStateCombinedSessionState, (CGKeyCode)53)) // escape
	        break;
	    
	    if (CGEventSourceKeyState(kCGEventSourceStateCombinedSessionState, (CGKeyCode)56)) // shift
            cs_insert_sound(ctx, &jump_instance);

	    if (CGEventSourceKeyState(kCGEventSourceStateCombinedSessionState, (CGKeyCode)58)) // option
			cs_insert_sound(ctx, &select_instance);

		cs_mix(ctx );
	}

	cs_free_sound(&jump_audio);
}

**Comment by RandyGaul** [comment]
Great, make a pull request for this and I'll merge it in!

**Comment by andykt** [comment]
Um, sorry, but I'm not sure how to do that, even after reading the GitHub docs.  I don't use GitHub all that much, mainly because I find the interface really confusing.  Anyway, my fix is a trivial one-line addition so I'm confident you'll know what to do. ;)

**Comment by RandyGaul** [comment]
1. Click fork

![image](https://user-images.githubusercontent.com/1919825/90228109-84d67180-ddca-11ea-9840-bb221e06a0d7.png)

2. Clone your fork

![image](https://user-images.githubusercontent.com/1919825/90228199-a8012100-ddca-11ea-9781-9266b973a63e.png)

3. Make a branch

`git checkout -b some_name_here`

4. Make your changes

5. Use `git add -u`, and also `git add some_new_folder/some_new_file.c`

6. Commit changes `git commit -m "stuff"`

7. Push to github `git push -u origin master`. This command is for the first time you push. From then on `git push` should work.

8. Make the pull request. Click this green button. This button will appear if you go to your fork in the web browser.

![image](https://user-images.githubusercontent.com/1919825/90228613-61f88d00-ddcb-11ea-9eae-b84c6144f956.png)

**Comment by fluffrabbit** [comment]
I like to use git add -A if I'm making big changes to the file structure.

**Comment by andykt** [comment]
Ok, I just did the pull request (only for the change to cute_sound.h).
I'll wait to see if that works before making any more contributions.

**Comment by RandyGaul** [comment]
Good work!

**Comment by RandyGaul** [comment]
Okay just closing this out, but your example does look quite nice. I can incorporate it in the future, but it's a little low priority for now. Please feel free to re-open this if you want to chat more, or make a pull request with your Apple demo!
