### ISSUE TITLE
cute_sound_pitch_plugin warning

### ISSUE THREAD

**Issue by Rafale25** [RandyGaul/cute_headers#219]
cute_sound_pitch_plugin.h line 49:
    #endif CUTE_SOUND_PITCH_PLUGIN_H

is making this warning : "warning: extra tokens at end of #endif directive"

define name should be commented like this :
    #endif // CUTE_SOUND_PITCH_PLUGIN_H

**Comment by RandyGaul** [comment]
Thanks! Please do add a pull request, it really helps :)

**Comment by RandyGaul** [comment]
Just cleaning up, feel free to re-open if needed.
