### ISSUE TITLE
Missing return in cute_math.h?

### ISSUE THREAD

**Issue by Greyvy** [RandyGaul/cute_headers#221]
https://github.com/RandyGaul/cute_headers/blob/804edee782ef0ce077b0834a414708245ecce604/cute_math.h#L200

Is there a missing return here? (should be: `__m128() const { return m; }`?). I get complaints while compiling with -Wall on clang++ macOS Mojave (10.14.6).

**Comment by RandyGaul** [comment]
Fixed https://github.com/RandyGaul/cute_headers/commit/2968d8880fcdff47651a1958733cc68746d9c6f8
