### ISSUE TITLE
cute_sound: Assertion failed in cs_mix when using CoreAudio at 48KHz

### ISSUE THREAD

**Issue by rogual** [RandyGaul/cute_headers#225]
There is an assertion that `samples_to_write` is divisible by 4, here:

```
2465		CUTE_SOUND_ASSERT(!(samples_to_write & 3));
```

This consistently fails for me on macOS 10.14 when I initialize cute_sound with a sample rate of 48000. If I use 44100, the assertion doesn't fail.

This seems to be caused by CoreAudio requesting 558 samples (in cs_memcpy_to_coreaudio, `inNumberFrames=558`). This then makes `ctx->samples_in_circular_buffer` non-divisible by 4, and ends up failing the assertion.

The requirement for divisibility by 4 looks like it comes from cute_sound's use of SIMD, which I don't know much about, so I can't tell if this is easily fixable or not.

**Comment by RandyGaul** [comment]
Thanks, I'm surprised I've never run into this issue myself, but it does make sense this is a possible bug. A solution needs to handle this case -- I'll work on it tomorrow. Thanks for reporting!

**Comment by RandyGaul** [comment]
Okay, give this a try. If it's still broken, please re-open the issue and let me know.

https://github.com/RandyGaul/cute_headers/commit/bccb5ebe2609ca280202d01c7711673861fdb983

**Comment by rogual** [comment]
Works great, thank you!
