### ISSUE TITLE
cute_sound does not compile on Visual Studio .NET a.k.a. 2003 due to missing stdint and InitializeCriticalSectionAndSpinCount

### ISSUE THREAD

**Issue by mijagourlay** [RandyGaul/cute_headers#234]
I have a use for cute_sound in a project that uses MS Visual Studio 2003. (This is a retro project that uses the original Xbox SDK and the last VisualStudio that supports it is 2003.) The cute_sound.h required some changes to compile:

Where stdint.h is included, I replaced it with this:

    #if ( _MSC_VER <= 1310 )    // Microsoft Visual Studio 2003 (.NET) C++ lacks stdint.
        typedef signed char        int8_t  ;
        typedef short              int16_t ;
        typedef int                int32_t ;
        typedef long long          int64_t ;
        typedef unsigned char      uint8_t  ;
        typedef unsigned short     uint16_t ;
        typedef unsigned int       uint32_t ;
        typedef unsigned long long uint64_t ;
    #else
        #include <stdint.h>
    #endif

Also, where InitializeCriticalSectionAndSpinCount is called, I replaced it with this:

    #if (_WIN32_WINNT >= 0x0403)
        InitializeCriticalSectionAndSpinCount(&ctx->critical_section, 0x00000400);
    #else
        InitializeCriticalSection(&ctx->critical_section);
    #endif

Besides that, there were a number of warnings that I disabled since this project treats them as errors. Also, I had to include some other headers. Also I had more trouble getting it to compile as a C file than as a CPP but I spent very little time trouble-shooting why since the project is predominantly C++. Here's the cpp I ended up with:

    #define CUTE_SOUND_IMPLEMENTATION
    #define _WIN32_WINNT 0x0403
    #include <windows.h>
    #include <winnt.h>
    #include <winbase.h>
    #pragma warning( disable: 4267 )    // 'initializing' : conversion from 'size_t' to 'unsigned char', possible loss of data
    #pragma warning( disable: 4127 )    // conditional expression is constant
    #include "cute_sound.h"

Also, the #define of _WIN32_WINNT to 0x0403 ends up making the #if for InitializeCriticalSectionAndSpinCount moot, but if I were being pedantic about being retro I'd have to use the pre-0403 API.

Also, I changed the hello demo to use another API to get the active window:

    //HWND hwnd = GetConsoleWindow();
        HWND hwnd = GetActiveWindow() ;
        if( 0 == hwnd ) return ;

I suspect approximately zero people will care about most of this, but the changes are so small that I figured I'd share just in case you elect to incorporate them into the canon.

**Comment by RandyGaul** [comment]
These look like nice adjustments! Please do throw up a pull request. You can easily make a request from the browser, here are some instructions I made https://github.com/RandyGaul/cute_headers/issues/215

**Comment by RandyGaul** [comment]
Closing for now. Free free to re-open if needed.
