### ISSUE TITLE
cute_sound: Load file without directly calling fopen [feature]

### ISSUE THREAD

**Issue by fluffrabbit** [RandyGaul/cute_headers#258]
In situations where calling the system fopen directly from cute_sound.h doesn't fit, such as when iterating over multiple candidates or loading from a tarball, there are a couple of solutions I can imagine.

A: Add `CUTE_SOUND_FOPEN` and `CUTE_SOUND_FCLOSE` macros, similar to how `CUTE_SOUND_ALLOC` is handled.

B: Do something like `stbi_load_from_file` which takes a `FILE` pointer.

Which is preferable?

**Comment by RandyGaul** [comment]
What about loading from memory function? Can open from tarball with a different function and pass the memory blob to open wav from memory?

**Comment by RandyGaul** [comment]
By the way I’m perfectly happy with your suggestion of macros for fopen/close, just curious on your thoughts about using the memory function instead.

**Comment by fluffrabbit** [comment]
Oy! Sounds like a good idea. Could you use this imaginary memory blob function in a code snippet?

My current solution (not currently applicable to cute_sound) is a drop-in fopen replacement. I'm not actually loading from tarballs or .pak files at this point. Any way to get sound loading into cute_sound without just giving the function a file name is good with me.

**Comment by fluffrabbit** [comment]
Sorry, don't know how I missed `cs_read_mem_wav` and `cs_read_mem_ogg`. Those do the thing!
