### ISSUE TITLE
aseprite 1.3-beta1: Failed assert "last_udata" in cute_aseprite.h:1089

### ISSUE THREAD

**Issue by RobLoach** [RandyGaul/cute_headers#259]
Aseprite 1.3-beta1 is available on Steam, and can be compiled by source too:
https://www.aseprite.org/beta/

When loading a 1.3-beta1 aseprite file, it runs into a failed assertion on line 1089. Here is a sample Aseprite 1.3-beta1 file....

[george.zip](https://github.com/RandyGaul/cute_headers/files/6562802/george.zip)

**Comment by RandyGaul** [comment]
I also heard there's a tilemap feature, so adding a parse path for tile stuff would be good too.

**Comment by RobLoach** [comment]
Make a small test_cute_aseprite.c file to help start this....
``` c
#include <assert.h>

#define CUTE_ASEPRITE_IMPLEMENTATION
#include "../cute_aseprite.h"

int main() {
    ase_t* ase = cute_aseprite_load_from_file("test.aseprite", NULL);
    assert(ase != NULL);

    int width = ase->w;
    int height = ase->h;
    assert(width == 64);
    assert(height == 64);

    cute_aseprite_free(ase);
}
```

**Comment by RandyGaul** [comment]
Seems like 1.3 stuff is still in beta version. Going to wait until a real release to do any updates here.

**Comment by RandyGaul** [comment]
Actually, I went ahead and added some 1.3 support. It doesn't parse tilesets (yet), but at least it shouldn't crash! Also added in some bugfixes for linked cels and hidden layers + layer groupings.

**Comment by RobLoach** [comment]
That's awesome news! I'll try it out and see whatever else I could add in. Thanks so much.

**Comment by RandyGaul** [comment]
I'm assuming there's no problems here? Feel free to re-open or comment if needed. I'll make a new issue about the tileset stuff.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/issues/289
