### ISSUE TITLE
cute_sound: Migrating from SDL_Mixer

### ISSUE THREAD

**Issue by VinnyVicious** [RandyGaul/cute_headers#268]
I'm currently migrating away from SDL_Mixer in favor of cute_sound because this library just rocks. The fact that it uses stb_vorbis is also awesome, so my project doesn't have to depend on crappy dependencies all over the place.

Unfortunately, I'm a little confused by the examples and could not find a replacement for the following functions:

- Mix_HaltChannel
- Mix_PlayChannel
- Mix_FadeInChannel
- Mix_FadeInChannelTimed
- Mix_PlayChannelTimed
- Mix_FadeOutChannel

**Comment by RandyGaul** [comment]
Cute sound is a bit lower level than those mix functions. There's no need for the concept of a channel, and fading functions would need to be implemented by you. If you want something a little higher level, or to just see an example of implementing some higher level stuff with cute sound, check out Cute Framework's audio API here: https://github.com/RandyGaul/cute_framework/blob/master/include/cute_audio.h

**Comment by VinnyVicious** [comment]
Thank you for the detailed answer and for sharing that, really appreciate it! You rock @RandyGaul :D
