### ISSUE TITLE
cute_sync POSIX untested / broken?

### ISSUE THREAD

**Issue by trapexit** [RandyGaul/cute_headers#270]
Is the posix version of cute_sync expected to work?

1. cute_semaphore_wait is broken. Calls "sem_try" (not a real function) rather than "sem_wait" so it doesn't even compile.
2. cute_semaphore_create calls sem_init((sem_t*)&semaphore.id,...) but that doesn't make sense given sizeof(sem_t) is 32 bytes on my system and sizeof(cute_semaphore_t) is 16. 
3. post,try,wait cast semaphore->id to sem_t* yet create casts &semaphore->id to sem_t*

**Comment by RandyGaul** [comment]
Ah I think I need to move the updated version in the cute framework repository here to fix these. Thanks for posting!

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/commit/2e57808956e537f6e904ce58372a515f4432fd31

Let me know if you find other issues!
