### ISSUE TITLE
cute_aseprite doesn't handle transparent palette indices

### ISSUE THREAD

**Issue by ingramb** [RandyGaul/cute_headers#274]
Composited frame pixels will be wrong if cells are using color indexed mode, and the palette doesn't have a transparent color set for the transparent index.  This shows up in some files I'm using at least.

Here is a proposed fix.  I'm not really git-literate, but I can try to figure out how to create a pull request if you prefer.

static ase_color_t s_color(ase_t* ase, void* src, int index)
{
    ase_color_t result;
    if (ase->mode == ASE_MODE_RGBA) {
        result = ((ase_color_t*)src)[index];
    }
    else if (ase->mode == ASE_MODE_GRAYSCALE) {
        uint8_t saturation = ((uint8_t*)src)[index * 2];
        uint8_t a = ((uint8_t*)src)[index * 2 + 1];
        result.r = result.g = result.b = saturation;
        result.a = a;
    }
    else {
        CUTE_ASEPRITE_ASSERT(ase->mode == ASE_MODE_INDEXED);
        uint8_t palette_index = ((uint8_t*)src)[index];
        if (palette_index == ase->transparent_palette_entry_index) {
            result = (ase_color_t) { 0, 0, 0, 0 };
        }
        else {
            result = ase->palette.entries[palette_index].color;
        }
    }
    return result;
}

**Comment by RandyGaul** [comment]
Hi there, thanks so much for making some code for the indexed feature. I'm happy to get this stuff in without a PR. What would be most helpful is to create a small program (a single .c file) you can paste here that loads an example indexed image. That way I can simply copy + paste in your changes, quickly spin up the debugger and verify things are working correctly. Then I can take care of pushing your code to master.

**Comment by ingramb** [comment]
The indexed images I found are here: https://rvros.itch.io/pixel-monsters-2.  Don't want to post the file here directly, as it's a paid pack, but if you email me at ingramb AT gmail, I can send you the file in question.
Simple program to load the file is cute_aseprite_load_from_file("mandrake.aseprite", NULL), not sure how helpful that is though :-)  I don't think I'll have time to put together a self contained example that actually visualizes the loaded sprite.

I'm not 100% sure that using transparent_palette_entry_index is correct here, but it seems reasonable.  I saw that is wasn't used anywhere else in cute_aseprite.  In the file I was using, it simply had a value of 0.  The file itself had the color (0,0,0,255) set into palette index 0.  Maybe this hasn't come up previously if most indexed files are stored with (0,0,0,0) as color0.

Anyway, without the updated code, it's pretty obvious what's going wrong, the composited frame image has black boxes around the different cell parts.

Also thanks for cute_aseprite!  Having a pipeline that avoids the need for extra export steps is a much better workflow.

**Comment by RandyGaul** [comment]
I've been swamped with other aspects of life and haven't been able to dedicate time lately to these GitHub issues. However, I can easily find spare time to look over pull requests from my phone and merge them in. It would be super helpful to get a PR here and in the other github issue you opened, if possible!

**Comment by RandyGaul** [comment]
Cool this looks correct!

https://github.com/RandyGaul/cute_headers/commit/8c6f78a0cc1e5aa3d76efb9e2fb867860ba1b032
