### ISSUE TITLE
cute_aseprite error parsing embedded ICC color profile

### ISSUE THREAD

**Issue by ingramb** [RandyGaul/cute_headers#278]
In cute_aseprite_load_from_memory,
When parsing this chunk: case 0x2007: // Color profile chunk.
After the CUTE_ASEPRITE_MEMCPY() copying the color profile data, you need to add this line to advance the input pointer past the data that was copied:
s->in += ase->color_profile.icc_profile_data_length;

Also I'd suggest adding an assert after parsing the chunk, to verify that the input pointer is equal to chunk_start+chunk_size, that will catch the problem closer to the actual cause.

**Comment by RandyGaul** [comment]
Make a pull request!

**Comment by RandyGaul** [comment]
Looks good!

https://github.com/RandyGaul/cute_headers/commit/388f001f54329669d95025700f2a0386bc53dd60
