### ISSUE TITLE
cute_spritebatch.h function declaration mismatch

### ISSUE THREAD

**Issue by meshula** [RandyGaul/cute_headers#279]
declared:

`void spritebatch_reset_function_ptrs(spritebatch_t* sb, submit_batch_fn* batch_callback, get_pixels_fn* get_pixels_callback, generate_texture_handle_fn* generate_texture_callback, destroy_texture_handle_fn* delete_texture_callback);`

implemented:

`void spritebatch_reset_function_ptrs(spritebatch_t* sb, submit_batch_fn* batch_callback, get_pixels_fn* get_pixels_callback, generate_texture_handle_fn* generate_texture_callback, destroy_texture_handle_fn* delete_texture_callback, sprites_sorter_fn* sprites_sorter_callback)`

**Comment by RandyGaul** [comment]
Same thing here -- will be able to merge in pull request from phone if it's possible to put one up! Would be very helpful!

**Comment by meshula** [comment]
https://github.com/RandyGaul/cute_headers/pull/285

**Comment by RandyGaul** [comment]
Thanks so much Nick!
