### ISSUE TITLE
cute_spritebatch.h use of bool

### ISSUE THREAD

**Issue by meshula** [RandyGaul/cute_headers#280]
MSVC 2019, compiling cute_spritebatch.h from a c file, couldn't compile this function

```
bool sprite_batch_internal_use_scratch_buffer(spritebatch_t* sb)
{
	return sb->sprites_sorter_callback == 0;
}
```

Had to add a `#include <stdbool.h>` to teach the compiler about bool.

**Comment by RandyGaul** [comment]
Same thing here -- will be able to merge in pull request from phone if it's possible to put one up! Would be very helpful!

**Comment by meshula** [comment]
https://github.com/RandyGaul/cute_headers/pull/285

**Comment by RandyGaul** [comment]
Thanks again Nick 😊
