### ISSUE TITLE
cute_asesprite.h - compilation by vs2019 c++ compiler

### ISSUE THREAD

**Issue by meshula** [RandyGaul/cute_headers#281]
including cute_asesprite.h from a cpp file under vs2019 doesn't work because of the C style initialization of the return value. tweaking the return as follows makes it c/c++ portable -

```cpp
static ase_color_t s_blend(ase_color_t src, ase_color_t dst, uint8_t opacity)
{
...
	ase_color_t ret = { (uint8_t)r, (uint8_t)g, (uint8_t)b, (uint8_t)a };
	return ret;
}
```

**Comment by RandyGaul** [comment]
Thank you very much! Possible to throw a pull request so I can merge it from phone?

**Comment by meshula** [comment]
Sure ~ https://github.com/RandyGaul/cute_headers/pull/282
