### ISSUE TITLE
cute_path.h: path_pop_ext produces incorrect result for relative paths

### ISSUE THREAD

**Issue by Captain4LK** [RandyGaul/cute_headers#283]
If there is a set of double dots anywhere except at the start of a path ('..', don't know what it's actually called), ``path_pop_ext`` produces an incorrect output. ``cf_get_ext`` from cute_files however, doesn't have this issue.
Here is a quick code snippet that causes the issue for me:

```C
#include <stdio.h>
#define CUTE_PATH_IMPLEMENTATION
#include "cute_path.h"
#define CUTE_FILES_IMPLEMENTATION
#include "cute_files.h"

int main(int argc, char **argv)
{
   const char *path = "../../test.txt";

   //cute_path
   char ext[33] = {0};
   path_pop_ext(path,NULL,ext);
   puts(ext);

   //cute_files
   cf_file_t file;
   strcpy(file.name,path);
   puts(cf_get_ext(&file));

   return 0;
}
```

Output (compiled with gcc):
```text
./test.txt
.txt
```

**Comment by RandyGaul** [comment]
Thanks so much for reporting this! I've been a bit busy lately with other things in life, but absolutely will fix this myself at some point, unless someone puts up a PR -- if we get a PR for this I can easily review it and merge it from my phone during the day when I have small bits of time.

**Comment by RandyGaul** [comment]
Thanks for the help there, your code change looked good at-a-glance!
