### ISSUE TITLE
cute_png.h: Saving a PNG to memory 

### ISSUE THREAD

**Issue by RicoP** [RandyGaul/cute_headers#316]
Similar to ```int cp_save_png(const char* file_name, const cp_image_t* img);``` it would be nice to have a 
```void * cp_save_png_to_mem(const cp_image_t* img, int * outBytes);``` that saves png byte array to a memory buffer. This would be very useful on systems that don't have disk access or when I just want to send a png as a byte stream over a network connection.

**Comment by RandyGaul** [comment]
Sure thing we can add this! Did you want to submit a PR? I can do this as well, but a PR may be faster.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/commit/0b2f66a0aff0d7e5db89c9d90554b96fd32c8457
