### ISSUE TITLE
cute_tiled: Problem with new default field "class" on Objects since Tiled 1.9

### ISSUE THREAD

**Issue by g-lujan** [RandyGaul/cute_headers#323]
Apparently, since Tiled 1.9, the field "class" is exported by default in the Objects on an Object Layer.

An example of a simple object inside an object layer:
![image](https://user-images.githubusercontent.com/23530029/197589007-12d77d48-4fa6-43d3-bbc0-854c80733878.png)

It breaks the function cute_tiled_load_map_from_file, making it return null even on very simple cases.

### **Steps to reproduce**
- On Tiled 1.9.2, create an object layer and add an object in the map. 
![image](https://user-images.githubusercontent.com/23530029/197585287-ba9ffb01-9abe-4cf9-97a8-6952eab13cdc.png)
- load this map with something like:
```c
cute_tiled_map_t* tiled_map = cute_tiled_load_map_from_file("my_map.json", NULL);
```
- The tiled_map will be null, as cute_tiled will fail to parse it with the "class" field. After removing this field manually, you will be able to load the map properly.

### **Proposed solution while "class" is not implemented**

Add the following case on the switch inside the function cute_tiled_read_object:
```c
case 1485919047363370797U: // class
	CUTE_TILED_WARNING("Class field of Tiled objects is not yet supported. Ignoring field.");	
        while (cute_tiled_peak(m) != ',' && cute_tiled_peak(m) != '}') cute_tiled_next(m);
	if (cute_tiled_peak(m) == '}')	continue;
	break;

```
This will ignore the field class when trying to read an object. The while is looking for both ',' and '}' to avoid breaking the parsing in case the user passes the field.

And add the following to the struct cute_tiled_object_t
```c
/* class */                          // Not currently supported.
```

**Comment by RandyGaul** [comment]
This looks great! Please add a pull request for this. Do you know how? I can send instructions — you can do it from the browser with just copy + paste.

**Comment by g-lujan** [comment]
@RandyGaul just submitted a PR. Thanks!!
