### ISSUE TITLE
[cute_net] Bug when sending reliable packets (repro code inside)

### ISSUE THREAD

**Issue by roig** [RandyGaul/cute_headers#329]
Just posting this to not lose the info/tracking about this bug :)

Bad behavior that we get: 
![imatge](https://user-images.githubusercontent.com/389619/199605684-bc10dbfb-22ce-4bae-bde9-90d1cdbace45.png)

We should be getting:
```
Client received packet_number: 0
Client received packet_number: 1
Client received packet_number: 2
Client received packet_number: 3
Client received packet_number: 4
Client received packet_number: 5
Client received packet_number: 6
Client received packet_number: 7
Client received packet_number: 8
Client received packet_number: 9
Client received packet_number: 10
Client received packet_number: 11
Client received packet_number: 12
```
Now it seems that when arrives to 8, it skips 8 packets.

Code to reproduce this bug: https://gist.github.com/roig/acfa68fa5e94aadd42f3ebeb783d8bcc

**Comment by RandyGaul** [comment]
Thanks! Very helpful of you to post this. I'm actually going to be working on this with a friend quite soon, so good timing.

**Comment by RandyGaul** [comment]
Should be fixed, please try it out when you can. Let me know if there are still issues!

https://github.com/RandyGaul/cute_headers/commit/bcfa78b801f53dbac18e09682e5a1e6193fdef14
