### ISSUE TITLE
Deprecate some older less useful headers

### ISSUE THREAD

**Issue by RandyGaul** [RandyGaul/cute_headers#331]
Specifically thinking to deprecate
* cute_time.h
* cute_alloc.h
* cute_filewatch.h
* cute_files.h
* cute_huff.h
* cute_font.h
* cute_path.h
* cute_math2d.h
* cute_memfile.h
* cute_utf.h

Some of these will be absorbed/relocated/replaced into [Cute Framework](https://github.com/RandyGaul/cute_framework) where they are better suited. Cute headers expanded over time, which is great, but these headers in particular are less useful, too niche, or belong in a higher level framework.

[This is the repository](https://github.com/RandyGaul/cute_headers_deprecated) where deprecated cute headers go. I'm always available to help anyone if they were using one of the deprecated headers, whether it be bug fixes or advice, but I won't be maintaining them with new features moving forward as they've fallen off my radar.

**Comment by RicoP** [comment]
Ok. At least  cute_filewatch.h and cute_files.h I am using quit frequently.

**Comment by RandyGaul** [comment]
Glad they're still useful! I just moved them over to the other repo. If you have problems with them I'm still here to help, I'm just not actively developing them anymore.
