### ISSUE TITLE
cute_aseprite: 1.3 Tilemap Support

### ISSUE THREAD

**Issue by RobLoach** [RandyGaul/cute_headers#338]
Aseprite 1.3 has some tilemap data that's saved. Would be awesome to load it! I saw [a note](https://github.com/RandyGaul/cute_headers/blob/73c6ced661fa429ce281f49b9cf4f20013cbb1f2/cute_aseprite.h#L46-L47) of it in the 1.3 parsing fix, so I thought I'd create an issue to track. 

Thanks! I may have some time to do some looking into it this month.

**Comment by RandyGaul** [comment]
I say go for it! It's low priority for me as I don't use these features, however, the parser is surprisingly easy to extend. Go ahead and open a PR and I can provide some technical guidance. It will likely take a lot less time than anticipated.

**Comment by RandyGaul** [comment]
Moved to https://github.com/RandyGaul/cute_headers/issues/350
