### ISSUE TITLE
Dynamically set panning for an individual playing sound

### ISSUE THREAD

**Issue by empyreanx** [RandyGaul/cute_headers#348]
Implement functions such as:
- float cs_sound_get_panning(cs_playing_sound_t sound)
- void cs_sound_set_panning(cs_playing_sound_t sound, float pan_0_to_1);

**Comment by RandyGaul** [comment]
Yeah we can definitely add this -- it should be pretty easy. Copying from another similar feature would be good:

```cpp
bool cs_sound_get_is_looped(cs_playing_sound_t sound)
{
	cs_sound_inst_t* inst = s_get_inst(sound);
	if (!inst) return false;
	return inst->looped;
}

void cs_sound_set_is_looped(cs_playing_sound_t sound, bool true_for_looped)
{
	cs_sound_inst_t* inst = s_get_inst(sound);
	if (!inst) return;
	inst->looped = true_for_looped;
}
```

**Comment by RandyGaul** [comment]
I will eventually get to implementing this (mostly just a copy + paste), but it's a bit low priority. If anyone wants this done now please do consider adding a PR!

**Comment by omicronrex** [comment]
Looks like this is already implemented currently? There are getters and setters for setting pan on instances in the current codebase.

**Comment by RandyGaul** [comment]
Thanks! We can probably just close this then.
