### ISSUE TITLE
cute_tiled: object `type` field

### ISSUE THREAD

**Issue by konsumer** [RandyGaul/cute_headers#362]
I swear this worked before, but I have objects like this:

<img width="222" alt="Screenshot 2023-10-15 at 5 07 38 PM" src="https://github.com/RandyGaul/cute_headers/assets/83857/bca21483-becb-41f6-966c-bdc1d4f18189">

I want the `Class` field to just show up as `object->type.ptr`. If I modify that class-parser part like this it works:

```c
case 1485919047363370797U: // class
  // CUTE_TILED_WARNING("Class field of Tiled objects is not yet supported. Ignoring field.");
  // while (cute_tiled_peak(m) != ',' && cute_tiled_peak(m) != '}') cute_tiled_next(m);
  // if (cute_tiled_peak(m) == '}') continue;
  cute_tiled_intern_string(m, &object->type);
  break;
```
Since there is no `type` field, it seems to me like a pretty safe overload.

Want a PR for this?

**Comment by RandyGaul** [comment]
Okay, sounds fine to me! PR is welcome.

**Comment by konsumer** [comment]
Some more notes on this:

I had a map that saved like this:

```json
"objects":[
    {
     "class":"player",
     "gid":1,
     "height":16,
     "id":1,
     "name":"",
     "rotation":0,
     "visible":true,
     "width":16,
     "x":384,
     "y":352
    }
```

Not even quite sure how I managed to save this, but it made all my code looking for `type` not work, so I think it may be some older compatibility setting, in save. The PR simply treats `class` as if it's `type`, since they seem to be interchangable.

**Comment by konsumer** [comment]
I think the source of the prob is [this](https://doc.mapeditor.org/en/stable/reference/json-map-format/):
```
type | string | The class of the object (was saved as class in 1.9, optional)

So, the field just got renamed in 1.9. Supporting both `type` and `class` and putting in `type` in the struct (as I do in PR) seems to be the correct behavior, to me.

**Comment by RandyGaul** [comment]
Thanks for the help!
