### ISSUE TITLE
cute_sound 2.x has no equivalent of 1.x cs_stop_sound

### ISSUE THREAD

**Issue by rogual** [RandyGaul/cute_headers#374]
I'm trying to upgrade from cute_sound 1.x to 2.x, but it seems the new API doesn't have a way to stop a sound like the old one did with `cs_stop_sound`.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/commit/d0e1f507d258350249623570b2c76a658e5ea9e8
