### ISSUE TITLE
Change of behaviour in c2TOI v1.10?

### ISSUE THREAD

**Issue by kyavi** [RandyGaul/cute_headers#392]
Previously c2TOI would return a TOI of 0 for shapes already intersecting. Now outside of the case of an impact happening with the given parameters (no intersection and the velocities causing an intersection) the new c2TOIResult always seems to resolve with `hit=0` and `toi=1`.

Is this intended? The only safe way to test seems to be calling `c2TOI` and then if `hit` is 0 also call `c2XXX_toXXX`?

**Comment by RandyGaul** [comment]
The c2TOI function was replaced with Erin's from Box2D, but, it should still be returning you a TOI of 0 if the shapes are already intersecting. Is it possible to copy + paste in a minimal example here to make it quick to hop on and take a look in the debugger for you?

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/cute_headers/commit/8c73bfe274feb4cc5a4c1f8d48d82059b8df5c24

Let me know if you still have issues!

**Comment by RandyGaul** [comment]
Awesome, here's another fix https://github.com/RandyGaul/cute_headers/commit/a0368a12064a6711a3271f219a7347d9b4c5b520

**Comment by RandyGaul** [comment]
Right yeah added toi = 0 to the if-statement just before the iteration loop. Should be good to go. Thanks for the help!

**Comment by RandyGaul** [comment]
Please report any other issues you find
