### ISSUE TITLE
cute_sound: Pitch Artifacts (SIMD Precision Issue) - Looking for Pull Request

### ISSUE THREAD

**Issue by AaronBalint** [RandyGaul/cute_headers#43]
I am having issues with playing the following (1.2 pitch setting): 
http://www.particle-space.xyz/downloads/gong.ogg

Substituting the following resolved the issue:

```
__m128 phase; // = _mm_atan2_ps( imag, real );
float *phasef = (float*)&phase;
float *realf = (float*)&real;
float *imagf = (float*)&imag;
for (int i=0; i<4; i++) phasef[i] = smbAtan2(imagf[i], realf[i]);
```

I suspect there is an issue with _mm_atan2_ps() related to the edge cases.

**Comment by RandyGaul** [comment]
Ah, yes. I'm pretty sure the precision of that function is not good outside the range of pi to -pi. There was the same problem with _mm_cos_ps. I'll have to implement a SIMD angle clamper before feeding values to the SIMD trig funcs.

Thanks Aaron!

**Comment by RandyGaul** [comment]
More info: https://handmade.network/forums/wip/t/1439-sse2_implementations_of_tan,_cot,_atan,_atan2

Seems this is a little more involved than I originally thought. I probably won't get the this for a long time if ever, but if someone else comes along and has the know-how, please do contribute!

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/commit/a68298fccceaf903a21e7bf943c14ddd17c950f3

**Comment by RandyGaul** [comment]
Super low priority -- just not doing these in SIMD is way easier of a solution. Going to close this out.
