### ISSUE TITLE
Add in null terminator for outputs in cu_shorten/cu_widen in cute_utf.h

### ISSUE THREAD

**Issue by ddengster** [RandyGaul/cute_headers#75]
I've been treating tuShorten/tuWiden as a string-ish conversion between UTF16 and UTF 8, so I recommend this.

Here's the code; add it to the end of every tuShorten/tuWiden function.
`if (out < (original_out + out_len))
    out = 0;`

**Comment by ddengster** [comment]
Also some feedback regarding your example tuWiden functions in https://github.com/RandyGaul/tinyheaders/issues/74#issuecomment-350167438

The 3rd and the 4th functions are likely going to be the most commonly used ones, the others are subsets of the 3rd and 4th function. I would use the 4th function on say, internal strings that I know are safe, but if I need extra validating (example: non-null terminated text from foreign sources) I can use the 3rd function.

**Comment by RandyGaul** [comment]
Did you mean:

    if (out < (original_out + out_len)) *out = 0;

**Comment by ddengster** [comment]
yes

**Comment by shreyabhandare** [comment]
Can i do this one?

**Comment by RandyGaul** [comment]
Yes of course :)

**Comment by shreyabhandare** [comment]
I can't seem to find tinyutf.h and what are tuShorten/tuWiden functions? do I need to read up something before i attempt to do this?

**Comment by sro5h** [comment]
The prefix of the header files changed to cute, so you‘re looking for `cute_utf.h`. I can‘t help you with your other question.

**Comment by shreyabhandare** [comment]
thanks, is there a way to test or build this once i make the changes?

**Comment by RandyGaul** [comment]
There is a little bit of testing here: https://github.com/RandyGaul/cute_headers/tree/master/test_cute_utf

If you like, you can add more tests in whatever manner you think makes sense. I would be more than happy to incorporate them if you write any down!

**Comment by RandyGaul** [comment]
Closing this out, as it's a bit outdated. I'll continue considering future changes to cute utf though, as it's used in [Cute Framework](https://github.com/RandyGaul/cute_framework)!
